using DevExpress.XtraPrinting.Localization;
using DevExpress.XtraRichEdit.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EBAP.Win.BaseFrame.Localization
{
    /// <summary>
    /// 미리보기 Control Library를 한국어로 설정합니다.
    /// </summary>
    internal class PPreviewLocalizer : DevExpress.XtraPrinting.Localization.PreviewLocalizer
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public override string GetLocalizedString(PreviewStringId id)
        {
            switch (id)
            {
                case PreviewStringId.Accessibility_Chart_Name: return " 차트";
                case PreviewStringId.Accessibility_Image_Name: return " 이미지";
                case PreviewStringId.Accessibility_Line_Name: return " 라인";
                case PreviewStringId.Accessibility_Shape_Name: return " 모양";
                case PreviewStringId.Accessibility_Sparkline_Name: return " 스파크 라인";
                case PreviewStringId.BarText_MainMenu: return " 메인 메뉴";
                case PreviewStringId.BarText_StatusBar: return " 상태 표시줄";
                case PreviewStringId.BarText_Toolbar: return " 도구 모음";
                case PreviewStringId.Button_Apply: return " 적용";
                case PreviewStringId.Button_Cancel: return " 취소";
                case PreviewStringId.Button_Help: return " 도움말";
                case PreviewStringId.Button_Ok: return " 확인";
                case PreviewStringId.DateRangeParameterEditor_LastMonth: return " 지난 달";
                case PreviewStringId.DateRangeParameterEditor_LastWeek: return " 지난 주";
                case PreviewStringId.DateRangeParameterEditor_Today: return " 오늘";
                case PreviewStringId.DateRangeParameterEditor_Yesterday: return " 어제";
                case PreviewStringId.EditingFieldEditorCategories_Numeric: return " 숫자";
                case PreviewStringId.EditingFieldEditors_Date: return " 날짜";
                case PreviewStringId.EditingFieldEditors_Image: return " 이미지";
                case PreviewStringId.EditingFieldEditors_OnlyLatinLetters: return " 라틴 편지";
                case PreviewStringId.EMail_From: return " 보낸 사람";
                case PreviewStringId.ExportOption_ConfirmationDoesNotMatchForm_Msg: return " 확인 암호는 일치 하지 않습니다. 다시 시작 하 고 암호를 다시 입력 하십시오.";
                case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Caption: return " 문서 열기 암호 확인";
                case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Name: return " 문서 열기 암호(&S):";
                case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Note: return " 문서 열기 암호를 확인 하십시오. 암호를 적어 해야 합니다. 문서를 여는 데 필요한 것입니다.";
                case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Caption: return " 사용 권한 암호 확인";
                case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Note: return " 권한 암호를 확인 하십시오. 암호를 적어 해야 합니다. 나중에 이러한 설정을 변경 하려면 필요 합니다.";
                case PreviewStringId.ExportOption_DocxExportMode: return " 내보내기 모드:";
                case PreviewStringId.ExportOption_DocxExportMode_SingleFile: return " 단일 파일";
                case PreviewStringId.ExportOption_DocxPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_HtmlCharacterSet: return " 문자 집합:";
                case PreviewStringId.ExportOption_HtmlEmbedImagesInHTML: return " HTML에 이미지 포함";
                case PreviewStringId.ExportOption_HtmlExportMode: return " 내보내기 모드:";
                case PreviewStringId.ExportOption_HtmlExportMode_DifferentFiles: return " 다른 파일";
                case PreviewStringId.ExportOption_HtmlExportMode_SingleFile: return " 단일 파일";
                case PreviewStringId.ExportOption_HtmlPageBorderColor: return " 페이지 테두리 색:";
                case PreviewStringId.ExportOption_HtmlPageBorderWidth: return " 페이지 테두리 폭:";
                case PreviewStringId.ExportOption_HtmlPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_HtmlRemoveSecondarySymbols: return " 캐리지 리턴 제거";
                case PreviewStringId.ExportOption_HtmlTableLayout: return " 테이블 레이아웃";
                case PreviewStringId.ExportOption_HtmlTitle: return " 제목:";
                case PreviewStringId.ExportOption_ImageExportMode: return " 내보내기 모드:";
                case PreviewStringId.ExportOption_ImageExportMode_DifferentFiles: return " 다른 파일";
                case PreviewStringId.ExportOption_ImageExportMode_SingleFile: return " 단일 파일";
                case PreviewStringId.ExportOption_ImageFormat: return " 이미지 형식:";
                case PreviewStringId.ExportOption_ImagePageBorderColor: return " 페이지 테두리 색:";
                case PreviewStringId.ExportOption_ImagePageBorderWidth: return " 페이지 테두리 폭:";
                case PreviewStringId.ExportOption_ImagePageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_ImageResolution: return " 해상도 (dpi):";
                case PreviewStringId.ExportOption_NativeFormatCompressed: return " 압축";
                case PreviewStringId.ExportOption_PdfACompatibility_None: return " 없음";
                case PreviewStringId.ExportOption_PdfChangingPermissions_AnyExceptExtractingPages: return " 어떤 페이지를 추출 하는 것 제외 하 고";
                case PreviewStringId.ExportOption_PdfChangingPermissions_CommentingFillingSigning: return " 주석 달기, 양식 필드에서 채우기 및 기존 서명 필드에 서명";
                case PreviewStringId.ExportOption_PdfChangingPermissions_FillingSigning: return " 양식 필드에서 채우기 및 기존 서명 필드에 서명";
                case PreviewStringId.ExportOption_PdfChangingPermissions_InsertingDeletingRotating: return " 페이지 삽입, 삭제 및 회전";
                case PreviewStringId.ExportOption_PdfChangingPermissions_None: return " 없음";
                case PreviewStringId.ExportOption_PdfConvertImagesToJpeg: return " Jpeg 이미지로 변환";
                case PreviewStringId.ExportOption_PdfDocumentApplication: return " 응용 프로그램:";
                case PreviewStringId.ExportOption_PdfDocumentAuthor: return " 작성자:";
                case PreviewStringId.ExportOption_PdfDocumentKeywords: return " 키워드:";
                case PreviewStringId.ExportOption_PdfDocumentSubject: return " 제목:";
                case PreviewStringId.ExportOption_PdfDocumentTitle: return " 제목:";
                case PreviewStringId.ExportOption_PdfImageQuality: return " 이미지 품질:";
                case PreviewStringId.ExportOption_PdfImageQuality_High: return " 높은";
                case PreviewStringId.ExportOption_PdfImageQuality_Highest: return " 최고";
                case PreviewStringId.ExportOption_PdfImageQuality_Low: return " 낮음";
                case PreviewStringId.ExportOption_PdfImageQuality_Lowest: return " 최저";
                case PreviewStringId.ExportOption_PdfImageQuality_Medium: return " 중간";
                case PreviewStringId.ExportOption_PdfNeverEmbeddedFonts: return " 이러한 글꼴을 포함 하지 않습니다.";
                case PreviewStringId.ExportOption_PdfPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions: return " 암호 보안:";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_DocumentOpenPassword: return " 문서 열기 암호";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_None: return " (없음)";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_Permissions: return " 사용 권한";
                case PreviewStringId.ExportOption_PdfPrintingPermissions_HighResolution: return " 높은 해상도";
                case PreviewStringId.ExportOption_PdfPrintingPermissions_LowResolution: return " 낮은 해상도 (150dpi)";
                case PreviewStringId.ExportOption_PdfPrintingPermissions_None: return " 없음";
                case PreviewStringId.ExportOption_PdfShowPrintDialogOnOpen: return " 열때 인쇄 대화 상자 표시";
                case PreviewStringId.ExportOption_PdfSignature_EmptyCertificate: return " 없음";
                case PreviewStringId.ExportOption_PdfSignature_Issuer: return " 발급자:";
                case PreviewStringId.ExportOption_PdfSignatureOptions: return " 디지털 서명:";
                case PreviewStringId.ExportOption_PdfSignatureOptions_Certificate: return " 인증서";
                case PreviewStringId.ExportOption_PdfSignatureOptions_ContactInfo: return " 연락처 정보";
                case PreviewStringId.ExportOption_PdfSignatureOptions_Image: return " 이미지";
                case PreviewStringId.ExportOption_PdfSignatureOptions_Location: return " 위치";
                case PreviewStringId.ExportOption_PdfSignatureOptions_None: return " (없음)";
                case PreviewStringId.ExportOption_PdfSignatureOptions_Reason: return " 이유";
                case PreviewStringId.ExportOption_PdfUACompatibility_None: return " 없음";
                case PreviewStringId.ExportOption_RtfExportMode: return " 내보내기 모드:";
                case PreviewStringId.ExportOption_RtfExportMode_SingleFile: return " 단일 파일";
                case PreviewStringId.ExportOption_RtfExportWatermarks: return " 워터 마크를 내보내기";
                case PreviewStringId.ExportOption_RtfPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_TextEncoding: return " 인코딩:";
                case PreviewStringId.ExportOption_TextExportMode: return " 텍스트 내보내기 모드:";
                case PreviewStringId.ExportOption_TextExportMode_Text: return " 텍스트";
                case PreviewStringId.ExportOption_TextExportMode_Value: return " 값";
                case PreviewStringId.ExportOption_TextQuoteStringsWithSeparators: return " 구분 기호 문자열을 인용";
                case PreviewStringId.ExportOption_TextSeparator: return " 텍스트 구분 기호:";
                case PreviewStringId.ExportOption_TextSeparator_TabAlias: return " 탭";
                case PreviewStringId.ExportOption_XlsExportHyperlinks: return " 하이퍼링크를 내보내기";
                case PreviewStringId.ExportOption_XlsExportMode: return " 내보내기 모드:";
                case PreviewStringId.ExportOption_XlsExportMode_DifferentFiles: return " 다른 파일";
                case PreviewStringId.ExportOption_XlsExportMode_SingleFile: return " 단일 파일";
                case PreviewStringId.ExportOption_XlsExportMode_SingleFilePageByPage: return " 단일 파일 페이지에 의해 페이지";
                case PreviewStringId.ExportOption_XlsPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_XlsRawDataMode: return " 원시 데이터 모드";
                case PreviewStringId.ExportOption_XlsSheetName: return " 시트 이름:";
                case PreviewStringId.ExportOption_XlsShowGridLines: return " 눈금선 표시";
                case PreviewStringId.ExportOption_XlsxExportMode: return " 내보내기 모드:";
                case PreviewStringId.ExportOption_XlsxExportMode_DifferentFiles: return " 다른 파일";
                case PreviewStringId.ExportOption_XlsxExportMode_SingleFile: return " 단일 파일";
                case PreviewStringId.ExportOption_XlsxExportMode_SingleFilePageByPage: return " 단일 파일 페이지에 의해 페이지";
                case PreviewStringId.ExportOption_XlsxPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOption_XpsCompression: return " 압축:";
                case PreviewStringId.ExportOption_XpsCompression_Fast: return " 빠른";
                case PreviewStringId.ExportOption_XpsCompression_Maximum: return " 최대";
                case PreviewStringId.ExportOption_XpsCompression_Normal: return " 보통";
                case PreviewStringId.ExportOption_XpsCompression_NotCompressed: return " 압축되지 않음";
                case PreviewStringId.ExportOption_XpsCompression_SuperFast: return " 초고속";
                case PreviewStringId.ExportOption_XpsDocumentCategory: return " 카테고리:";
                case PreviewStringId.ExportOption_XpsDocumentCreator: return " 작성자:";
                case PreviewStringId.ExportOption_XpsDocumentDescription: return " 설명:";
                case PreviewStringId.ExportOption_XpsDocumentKeywords: return " 키워드:";
                case PreviewStringId.ExportOption_XpsDocumentSubject: return " 제목:";
                case PreviewStringId.ExportOption_XpsDocumentTitle: return " 제목:";
                case PreviewStringId.ExportOption_XpsDocumentVersion: return " 버전:";
                case PreviewStringId.ExportOption_XpsPageRange: return " 페이지 범위:";
                case PreviewStringId.ExportOptionsForm_CaptionCsv: return " CSV 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionHtml: return " HTML 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionImage: return " 이미지 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionMht: return " MHT 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionNativeOptions: return " 네이티브 형식 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionPdf: return " PDF 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionRtf: return " RTF 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionTxt: return " 텍스트 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionXls: return " XLS 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionXlsx: return " XLSX 내보내기 옵션";
                case PreviewStringId.ExportOptionsForm_CaptionXps: return " XPS 내보내기 옵션";
                case PreviewStringId.FolderBrowseDlg_ExportDirectory: return " 내보낸된 문서를 저장할 폴더를 선택:";
                case PreviewStringId.ImageEditingFieldEditor_Alignment: return " 맞춤";
                case PreviewStringId.ImageEditingFieldEditor_Clear: return " 지우기";
                case PreviewStringId.ImageEditingFieldEditor_Reset: return " 다시 설정";
                case PreviewStringId.Margin_BottomMargin: return " 아래쪽 여백";
                case PreviewStringId.Margin_Inch: return " 인치";
                case PreviewStringId.Margin_LeftMargin: return " 왼쪽 여백";
                case PreviewStringId.Margin_Millimeter: return " mm";
                case PreviewStringId.Margin_Pixel: return " px";
                case PreviewStringId.Margin_RightMargin: return " 오른쪽 여백";
                case PreviewStringId.Margin_TopMargin: return " 위쪽 여백";
                case PreviewStringId.MenuItem_BackgrColor: return " 색상(&C)...";
                case PreviewStringId.MenuItem_Background: return " 배경(&B)";
                case PreviewStringId.MenuItem_Copy: return " 복사";
                case PreviewStringId.MenuItem_CsvDocument: return " CSV 파일";
                case PreviewStringId.MenuItem_Exit: return " 종료(&X)";
                case PreviewStringId.MenuItem_Export: return " 내보내기 (&E)";
                case PreviewStringId.MenuItem_File: return " 파일(&F)";
                case PreviewStringId.MenuItem_GraphicDocument: return " 이미지 파일";
                case PreviewStringId.MenuItem_HtmDocument: return " HTML 파일";
                case PreviewStringId.MenuItem_MhtDocument: return " MHT 파일";
                case PreviewStringId.MenuItem_PageLayout: return " 페이지 레이아웃(&P)";
                case PreviewStringId.MenuItem_PageSetup: return " 페이지 설정(&U)...";
                case PreviewStringId.MenuItem_PdfDocument: return " PDF 파일";
                case PreviewStringId.MenuItem_Print: return " 인쇄 (&P)...";
                case PreviewStringId.MenuItem_PrintDirect: return " 인쇄(&R)";
                case PreviewStringId.MenuItem_RtfDocument: return " RTF 파일";
                case PreviewStringId.MenuItem_TxtDocument: return " 텍스트 파일";
                case PreviewStringId.MenuItem_View: return " 보기(&V)";
                case PreviewStringId.MenuItem_ViewContinuous: return " 연속(&C)";
                case PreviewStringId.MenuItem_ViewStatusbar: return " 상태 표시줄";
                case PreviewStringId.MenuItem_ViewToolbar: return " 도구 모음(&T)";
                case PreviewStringId.MenuItem_Watermark: return " 워터 마크(&W)...";
                case PreviewStringId.MenuItem_XlsDocument: return " XLS 파일";
                case PreviewStringId.MenuItem_XlsxDocument: return " XLSX 파일";
                case PreviewStringId.MenuItem_ZoomPageWidth: return " 페이지 너비";
                case PreviewStringId.MenuItem_ZoomTextWidth: return " 텍스트 너비";
                case PreviewStringId.MenuItem_ZoomTwoPages: return " 두 페이지";
                case PreviewStringId.MenuItem_ZoomWholePage: return " 전체 페이지";
                case PreviewStringId.MPForm_Lbl_Pages: return " 페이지";
                case PreviewStringId.Msg_BigBitmapToCreate: return " 출력 파일 너무 큽니다. 이미지의 해상도 줄이기 위해 시도 하십시오. 다른 내보내기 모드 선택 또는.";
                case PreviewStringId.Msg_BigFileToCreate: return " 출력 파일 너무 큽니다. 그것의 페이지 수를 줄이기 위해 또는 여러 문서에 그것을 분할 하려고 합니다.";
                case PreviewStringId.Msg_BigFileToCreateJPEG: return " 출력 파일은 너무 큰 JPEG 파일을 만듭니다. 다른 이미지 포맷 또는 다른 내보내기 모드를 선택 하십시오.";
                case PreviewStringId.Msg_CannotAccessFile: return " 프로세스 다른 프로세스에 의해 사용 되 고 있기 때문에 파일 {0} 에 액세스할 수 없습니다.";
                case PreviewStringId.Msg_CannotFindFile: return " 지정 된 작업을 수행할 수 없습니다. 다음 라이브러리는 누락: {0} ";
                case PreviewStringId.Msg_CannotLoadDocument: return " 지정한 파일 로드할 수 없습니다, 그것은 유효한 XML 데이터를 포함 하지 않습니다 또는 허용 된 크기를 초과 하기 때문에.";
                case PreviewStringId.Msg_CantFitBarcodeToControlBounds: return " 컨트롤의 테두리가 너무 좁아서 바코드를 만들 수 없습니다.";
                case PreviewStringId.Msg_Caption: return " 인쇄";
                case PreviewStringId.Msg_CreatingDocument: return " 문서 만들기...";
                case PreviewStringId.Msg_CustomDrawWarning: return " 경고!";
                case PreviewStringId.Msg_EmptyDocument: return " 이 문서는 페이지가 없습니다.";
                case PreviewStringId.Msg_ErrorTitle: return " 오류";
                case PreviewStringId.Msg_FileDoesNotHavePrnxExtension: return " 지정한 파일 PRNX 확장을 필요 하지 않습니다. 계속 진행?";
                case PreviewStringId.Msg_FontInvalidNumber: return " 글꼴 크기는 0 또는 음수 번호를 설정할 수 없습니다";
                case PreviewStringId.Msg_GoToNonExistentPage: return " 이 문서에 없는 페이지 번호 {0} 입니다.";
                case PreviewStringId.Msg_IncorrectPageRange: return " 이것은 유효한 페이지 범위가 없습니다.";
                case PreviewStringId.Msg_IncorrectZoomFactor: return " {0}과 {1} 사이 여야 합니다.";
                case PreviewStringId.Msg_InvalidBarcodeData: return " 이진 데이터는 {0} 바이트를 초과 할 수 없습니다.";
                case PreviewStringId.Msg_InvalidBarcodeText: return " 텍스트에 잘못된 문자가 포함되어 있습니다.";
                case PreviewStringId.Msg_InvalidBarcodeTextFormat: return " 잘못 된 텍스트 형식";
                case PreviewStringId.Msg_InvPropName: return " 잘못 된 속성 이름";
                case PreviewStringId.Msg_NeedPrinter: return " 설치 된 프린터 없음.";
                case PreviewStringId.Msg_NoDifferentFilesInStream: return " A 문서는 DifferentFiles 모드에서 스트림에 내보낼 수 없습니다. SingleFile 또는 SingleFilePageByPage 모드를 대신 사용 합니다.";
                case PreviewStringId.Msg_NotSupportedFont: return " 이 글꼴은 아직 지원되지 않습니다.";
                case PreviewStringId.Msg_OpenFileQuestion: return " 이 파일을 여시겠습니까?";
                case PreviewStringId.Msg_OpenFileQuestionCaption: return " 내보내기";
                case PreviewStringId.Msg_PageMarginsWarning: return " 페이지의 인쇄 가능 영역 외부에 하나 이상의 여백이 설정되어 있습니다. 작업을 계속 하시겠습니까?";
                case PreviewStringId.Msg_Progress_Printing: return " 인쇄";
                case PreviewStringId.Msg_Search_Caption: return " 검색";
                case PreviewStringId.Msg_SeparatorCannotBeEmptyString: return " 구분 기호는 빈 문자열일 수 없습니다.";
                case PreviewStringId.Msg_UnavailableNetPrinter: return " 네트워크 프린터는 사용할 수 없습니다.";
                case PreviewStringId.Msg_WrongPageSettings: return " 현재 프린터 선택한 용지 크기를 지원 하지 않습니다. 계속 진행 ? ";
                case PreviewStringId.Msg_WrongPrinter: return " 프린터 이름이 올바르지 않습니다. 프린터 설정을 확인 하시기 바랍니다.";
                case PreviewStringId.Msg_WrongPrinting: return " 문서를 인쇄 하는 동안 오류가 발생 했습니다.";
                case PreviewStringId.NoneString: return " (없음)";
                case PreviewStringId.OpenFileDialog_Filter: return " 미리 보기 문서 파일 (* {0}) | * {0} |모든 파일 (*. *) | *. *";
                case PreviewStringId.OpenFileDialog_Title: return " 열기";
                case PreviewStringId.PageInfo_PageDate: return " [날짜 인쇄]";
                case PreviewStringId.PageInfo_PageNumber: return " [# 페이지]";
                case PreviewStringId.PageInfo_PageNumberOfTotal: return " [페이지 페이지의 # #]";
                case PreviewStringId.PageInfo_PageTime: return " [인쇄 시간]";
                case PreviewStringId.PageInfo_PageTotal: return " [# 페이지]";
                case PreviewStringId.PageInfo_PageUserName: return " [사용자 이름]";
                case PreviewStringId.ParameterLookUpSettingsNoLookUp: return " 검색 없음";
                case PreviewStringId.ParametersRequest_Caption: return " 매개 변수";
                case PreviewStringId.ParametersRequest_NullValuePrompt: return " (없음)";
                case PreviewStringId.ParametersRequest_Reset: return " 다시 설정";
                case PreviewStringId.ParametersRequest_Submit: return " 제출";
                case PreviewStringId.PreviewForm_Caption: return " 미리 보기";
                case PreviewStringId.PrintDialog_Duplex_Horizontal: return " 짧은 가장자리 대칭 이동";
                case PreviewStringId.PrintDialog_Duplex_Simplex: return " 없음";
                case PreviewStringId.PrintDialog_Duplex_Vertical: return " 긴 가장자리에 대칭 이동";
                case PreviewStringId.PrinterStatus_Busy: return " 프린터 중임.";
                case PreviewStringId.PrinterStatus_DoorOpen: return " 프린터 문이 열려있지.";
                case PreviewStringId.PrinterStatus_Error: return " 오류";
                case PreviewStringId.PrinterStatus_IOActive: return " 프린터의 입력/출력 활성은.";
                case PreviewStringId.PrinterStatus_NotAvailable: return " 프린터는 사용할 수 없습니다.";
                case PreviewStringId.PrinterStatus_Offline: return " 프린터 오프 라인 상태입니다.";
                case PreviewStringId.PrinterStatus_OutputBinFull: return " 출력 함이 가득 차 있다.";
                case PreviewStringId.PrinterStatus_Paused: return " 프린터가 일시 중지되었습니다.";
                case PreviewStringId.PrinterStatus_PowerSave: return " 에 전원 절약 모드입니다.";
                case PreviewStringId.PrinterStatus_Processing: return " 처리...";
                case PreviewStringId.PrinterStatus_ServerUnknown: return " 서버를 알 수 없습니다.";
                case PreviewStringId.PrinterStatus_TonerLow: return " 토너가 부족합니다.";
                case PreviewStringId.PrinterStatus_UserIntervention: return " 사용자 개입 발생 했습니다.";
                case PreviewStringId.ReportDesignAnalyzer_GridColumn_Description: return " 설명";
                case PreviewStringId.RibbonPreview_ClosePreview_Caption: return " 인쇄 미리 보기 닫기";
                case PreviewStringId.RibbonPreview_ClosePreview_STipContent: return " 문서의 인쇄 미리 보기 닫기.";
                case PreviewStringId.RibbonPreview_ClosePreview_STipTitle: return " 인쇄 미리 보기 닫기";
                case PreviewStringId.RibbonPreview_Customize_Caption: return " 옵션";
                case PreviewStringId.RibbonPreview_Customize_STipContent: return " 인쇄 옵션을 변경할 수 있습니다 인쇄 옵션 대화 상자를 엽니다.";
                case PreviewStringId.RibbonPreview_Customize_STipTitle: return " 옵션";
                case PreviewStringId.RibbonPreview_DocumentMap_Caption: return " 책갈피";
                case PreviewStringId.RibbonPreview_DocumentMap_STipContent: return " 오픈 문서 구조를 문서 구조 보기를 탐색할 수 있습니다.";
                case PreviewStringId.RibbonPreview_DocumentMap_STipTitle: return " 문서 구조";
                case PreviewStringId.RibbonPreview_EditPageHF_Caption: return " 머리글/바닥글";
                case PreviewStringId.RibbonPreview_EditPageHF_STipContent: return " 문서의 머리글과 바닥글을 편집합니다.";
                case PreviewStringId.RibbonPreview_EditPageHF_STipTitle: return " 머리글 및 바닥글";
                case PreviewStringId.RibbonPreview_ExportCsv_Caption: return " CSV 파일";
                case PreviewStringId.RibbonPreview_ExportCsv_Description: return " 쉼표로 구분 된 텍스트";
                case PreviewStringId.RibbonPreview_ExportCsv_STipContent: return " CSV로 문서를 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportCsv_STipTitle: return " CSV로 내보내기";
                case PreviewStringId.RibbonPreview_ExportFile_Caption: return " 내보내기";
                case PreviewStringId.RibbonPreview_ExportFile_STipContent: return " 사용할 수 있는 형식 중 하나로 현재 문서를 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportFile_STipTitle: return " 내보내기...";
                case PreviewStringId.RibbonPreview_ExportGraphic_Caption: return " 이미지 파일";
                case PreviewStringId.RibbonPreview_ExportGraphic_Description: return " BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
                case PreviewStringId.RibbonPreview_ExportGraphic_STipContent: return " 이미지 문서를 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportGraphic_STipTitle: return " 이미지 내보내기";
                case PreviewStringId.RibbonPreview_ExportHtm_Caption: return " HTML 파일";
                case PreviewStringId.RibbonPreview_ExportHtm_Description: return " 웹 페이지";
                case PreviewStringId.RibbonPreview_ExportHtm_STipContent: return " 문서를 HTML로 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportHtm_STipTitle: return " HTML로 내보내기";
                case PreviewStringId.RibbonPreview_ExportMht_Caption: return " MHT 파일";
                case PreviewStringId.RibbonPreview_ExportMht_Description: return " 단일 파일 웹 페이지";
                case PreviewStringId.RibbonPreview_ExportMht_STipContent: return " Mht 문서를 수출 하 고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportMht_STipTitle: return " MHT로 내보내기";
                case PreviewStringId.RibbonPreview_ExportPdf_Caption: return " PDF 파일";
                case PreviewStringId.RibbonPreview_ExportPdf_Description: return " Adobe 휴대용 문서 형식";
                case PreviewStringId.RibbonPreview_ExportPdf_STipContent: return " PDF로 문서를 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportPdf_STipTitle: return " PDF로 내보내기";
                case PreviewStringId.RibbonPreview_ExportRtf_Caption: return " RTF 파일";
                case PreviewStringId.RibbonPreview_ExportRtf_Description: return " 서식 있는 텍스트 형식";
                case PreviewStringId.RibbonPreview_ExportRtf_STipContent: return " RTF 형식으로 문서를 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportRtf_STipTitle: return " RTF로 내보내기";
                case PreviewStringId.RibbonPreview_ExportTxt_Caption: return " 텍스트 파일";
                case PreviewStringId.RibbonPreview_ExportTxt_Description: return " 일반 텍스트";
                case PreviewStringId.RibbonPreview_ExportTxt_STipContent: return " 텍스트 문서를 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportTxt_STipTitle: return " 텍스트 내보내기";
                case PreviewStringId.RibbonPreview_ExportXls_Caption: return " XLS 파일";
                case PreviewStringId.RibbonPreview_ExportXls_Description: return " Microsoft Excel 2000-2003 통합 문서";
                case PreviewStringId.RibbonPreview_ExportXls_STipContent: return " 문서 XLS 내보내고 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportXls_STipTitle: return " XLS로 내보내기";
                case PreviewStringId.RibbonPreview_ExportXlsx_Caption: return " XLSX 파일";
                case PreviewStringId.RibbonPreview_ExportXlsx_Description: return " Microsoft Excel 통합 문서";
                case PreviewStringId.RibbonPreview_ExportXlsx_STipContent: return " XLSX 문서 내보내기 및 디스크에 파일을 저장 합니다.";
                case PreviewStringId.RibbonPreview_ExportXlsx_STipTitle: return " XLSX로 내보내기";
                case PreviewStringId.RibbonPreview_ExportXps_Caption: return " XPS 파일";
                case PreviewStringId.RibbonPreview_ExportXps_Description: return " XPS";
                case PreviewStringId.RibbonPreview_FillBackground_Caption: return " 페이지 색";
                case PreviewStringId.RibbonPreview_FillBackground_STipContent: return " 문서 페이지의 배경 색상을 선택 하십시오.";
                case PreviewStringId.RibbonPreview_FillBackground_STipTitle: return " 배경 색상";
                case PreviewStringId.RibbonPreview_Find_Caption: return " 찾기";
                case PreviewStringId.RibbonPreview_Find_STipContent: return " 텍스트를 찾으려면 문서에서 찾기 대화 상자를 표시 합니다.";
                case PreviewStringId.RibbonPreview_Find_STipTitle: return " 찾기";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMargins_Description: return " 탑: 하단 {0}: {1} : 좌우 {2}: {3} ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Caption: return " 적당한";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Description: return " 적당한";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Caption: return " 좁은";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Description: return " 좁은";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Caption: return " 보통";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Description: return " 보통";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Caption: return " 넓은";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Description: return " 넓은";
                case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Caption: return " 가로";
                case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Caption: return " 세로";
                case PreviewStringId.RibbonPreview_GalleryItem_PaperSize_Description: return " {0} x {1}";
                case PreviewStringId.RibbonPreview_HandTool_Caption: return " 손 도구";
                case PreviewStringId.RibbonPreview_HandTool_STipContent: return " 수동으로 페이지를 손 도구를 호출 합니다.";
                case PreviewStringId.RibbonPreview_HandTool_STipTitle: return " 손 도구";
                case PreviewStringId.RibbonPreview_HighlightEditingFields_Caption: return " 필드 편집";
                case PreviewStringId.RibbonPreview_HighlightEditingFields_STipContent: return " 하이라이트 모든 편집을 신속 하 게 발견 문서 요소는 편집 가능한 필드.";
                case PreviewStringId.RibbonPreview_HighlightEditingFields_STipTitle: return " 편집 필드 강조";
                case PreviewStringId.RibbonPreview_Magnifier_Caption: return " 돋보기";
                case PreviewStringId.RibbonPreview_Magnifier_STipContent: return " 호출 돋보기 도구입니다. 그것은 단일 페이지 완전히 표시 되도록 확대 문서에 한 번 클릭, 클릭 하는 동안 다른 시간 확대 그것은 정상적인 크기의 100 %.";
                case PreviewStringId.RibbonPreview_Magnifier_STipTitle: return " 돋보기";
                case PreviewStringId.RibbonPreview_MultiplePages_Caption: return " 여러 페이지";
                case PreviewStringId.RibbonPreview_MultiplePages_STipContent: return " 페이지 레이아웃을 선택하고 미리보기에서 문서의 페이지를 배치합니다.";
                case PreviewStringId.RibbonPreview_MultiplePages_STipTitle: return " 여러 페이지를 표시";
                case PreviewStringId.RibbonPreview_Open_Caption: return " 열기";
                case PreviewStringId.RibbonPreview_Open_STipContent: return " 문서를 엽니다.";
                case PreviewStringId.RibbonPreview_Open_STipTitle: return " 열기 (Ctrl + O)";
                case PreviewStringId.RibbonPreview_PageGroup_Background: return " 페이지 배경";
                case PreviewStringId.RibbonPreview_PageGroup_Close: return " 닫기";
                case PreviewStringId.RibbonPreview_PageGroup_Document: return " 문서";
                case PreviewStringId.RibbonPreview_PageGroup_Export: return " 내보내기";
                case PreviewStringId.RibbonPreview_PageGroup_Navigation: return " 탐색";
                case PreviewStringId.RibbonPreview_PageGroup_PageSetup: return " 페이지 설정";
                case PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipContent: return " 페이지 설정 대화 상자를 표시 합니다.";
                case PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipTitle: return " 페이지 설정";
                case PreviewStringId.RibbonPreview_PageGroup_Print: return " 인쇄";
                case PreviewStringId.RibbonPreview_PageGroup_Zoom: return " 확대/축소";
                case PreviewStringId.RibbonPreview_PageMargins_Caption: return " 여백";
                case PreviewStringId.RibbonPreview_PageMargins_STipContent: return "선택 여백 크기. 문서에 특정 여백 크기를 적용 하려면 사용자 지정 여백을 클릭 합니다.";
                case PreviewStringId.RibbonPreview_PageMargins_STipTitle: return " 페이지 여백";
                case PreviewStringId.RibbonPreview_PageOrientation_Caption: return " 방향";
                case PreviewStringId.RibbonPreview_PageOrientation_STipContent: return " 페이지 가로 및 세로 레이아웃 사이 전환 합니다.";
                case PreviewStringId.RibbonPreview_PageOrientation_STipTitle: return " 페이지 방향";
                case PreviewStringId.RibbonPreview_PageSetup_Caption: return " 사용자 지정 여백...";
                case PreviewStringId.RibbonPreview_PageSetup_STipContent: return " 페이지 설정 대화 상자를 표시 합니다.";
                case PreviewStringId.RibbonPreview_PageSetup_STipTitle: return " 페이지 설정";
                case PreviewStringId.RibbonPreview_PageText: return " 인쇄 미리 보기";
                case PreviewStringId.RibbonPreview_PaperSize_Caption: return " 크기";
                case PreviewStringId.RibbonPreview_PaperSize_STipContent: return " 문서의 용지 크기를 선택 합니다.";
                case PreviewStringId.RibbonPreview_PaperSize_STipTitle: return " 페이지 크기";
                case PreviewStringId.RibbonPreview_Parameters_Caption: return " 매개 변수";
                case PreviewStringId.RibbonPreview_Parameters_STipContent: return " 보고서 매개 변수에 대 한 값을 입력 하면 매개 변수 창을 엽니다.";
                case PreviewStringId.RibbonPreview_Parameters_STipTitle: return " 매개 변수";
                case PreviewStringId.RibbonPreview_Pointer_Caption: return " 포인터";
                case PreviewStringId.RibbonPreview_Pointer_STipContent: return " 마우스 포인터를 표시 합니다.";
                case PreviewStringId.RibbonPreview_Pointer_STipTitle: return " 마우스 포인터";
                case PreviewStringId.RibbonPreview_Print_Caption: return " 인쇄";
                case PreviewStringId.RibbonPreview_Print_STipContent: return " 프린터, 사본의 수 및 인쇄 하기 전에 다른 인쇄 옵션을 선택 합니다.";
                case PreviewStringId.RibbonPreview_Print_STipTitle: return " 인쇄 (Ctrl + P)";
                case PreviewStringId.RibbonPreview_PrintDirect_Caption: return " 빠른 인쇄";
                case PreviewStringId.RibbonPreview_PrintDirect_STipContent: return " 직접 기본 프린터 변경 하지 않고 문서를 보냅니다.";
                case PreviewStringId.RibbonPreview_PrintDirect_STipTitle: return " 빠른 인쇄";
                case PreviewStringId.RibbonPreview_Save_Caption: return " 저장";
                case PreviewStringId.RibbonPreview_Save_STipContent: return " 문서를 저장합니다.";
                case PreviewStringId.RibbonPreview_Save_STipTitle: return " 저장 (Ctrl + S)";
                case PreviewStringId.RibbonPreview_Scale_Caption: return " 배율";
                case PreviewStringId.RibbonPreview_Scale_STipContent: return " 스트레치 또는 축소 인쇄 출력 그것의 실제 크기의 백분율에.";
                case PreviewStringId.RibbonPreview_Scale_STipTitle: return " 규모";
                case PreviewStringId.RibbonPreview_SendCsv_Caption: return " CSV 파일";
                case PreviewStringId.RibbonPreview_SendCsv_Description: return " 쉼표로 구분 된 텍스트";
                case PreviewStringId.RibbonPreview_SendCsv_STipContent: return " 문서를 CSV로 내보내기 및 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendCsv_STipTitle: return " CSV로 전자 메일";
                case PreviewStringId.RibbonPreview_SendFile_Caption: return " 전자 메일";
                case PreviewStringId.RibbonPreview_SendFile_STipContent: return " 사용할 수 있는 형식 중 하나에서 현재 문서를 내보내고 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendFile_STipTitle: return " 전자 메일...";
                case PreviewStringId.RibbonPreview_SendGraphic_Caption: return " 이미지 파일";
                case PreviewStringId.RibbonPreview_SendGraphic_Description: return " BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
                case PreviewStringId.RibbonPreview_SendGraphic_STipContent: return " 문서를 이미지로 내보내고 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendGraphic_STipTitle: return " 전자 메일 이미지";
                case PreviewStringId.RibbonPreview_SendMht_Caption: return " MHT 파일";
                case PreviewStringId.RibbonPreview_SendMht_Description: return " 단일 파일 웹 페이지";
                case PreviewStringId.RibbonPreview_SendMht_STipContent: return " 문서를 MHT로 내보내고 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendMht_STipTitle: return " MHT로 전자 메일";
                case PreviewStringId.RibbonPreview_SendPdf_Caption: return " PDF 파일";
                case PreviewStringId.RibbonPreview_SendPdf_Description: return " 어도비 휴대용 문서 형식";
                case PreviewStringId.RibbonPreview_SendPdf_STipContent: return " PDF로 문서를 내보내고 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendPdf_STipTitle: return " PDF로 전자 메일";
                case PreviewStringId.RibbonPreview_SendRtf_Caption: return " RTF 파일";
                case PreviewStringId.RibbonPreview_SendRtf_Description: return " 서식 있는 텍스트 형식";
                case PreviewStringId.RibbonPreview_SendRtf_STipContent: return " Rtf 형식으로 문서를 내보내고 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendTxt_Caption: return " 텍스트 파일";
                case PreviewStringId.RibbonPreview_SendTxt_Description: return " 일반 텍스트";
                case PreviewStringId.RibbonPreview_SendTxt_STipContent: return " 텍스트 문서를 내보내고 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendTxt_STipTitle: return " 텍스트로 전자 메일";
                case PreviewStringId.RibbonPreview_SendXls_Caption: return " XLS 파일";
                case PreviewStringId.RibbonPreview_SendXls_Description: return " Microsoft Excel 2000-2003 통합 문서";
                case PreviewStringId.RibbonPreview_SendXls_STipContent: return " XLS 문서 내보내기 및 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendXls_STipTitle: return " XLS로 전자 메일";
                case PreviewStringId.RibbonPreview_SendXlsx_Caption: return " XLSX 파일";
                case PreviewStringId.RibbonPreview_SendXlsx_Description: return " Microsoft Excel 통합 문서";
                case PreviewStringId.RibbonPreview_SendXlsx_STipContent: return " XLSX 문서 내보내기 및 전자 메일에 첨부 합니다.";
                case PreviewStringId.RibbonPreview_SendXlsx_STipTitle: return " XLSX로 전자 메일";
                case PreviewStringId.RibbonPreview_SendXps_Caption: return " XPS 파일";
                case PreviewStringId.RibbonPreview_SendXps_Description: return " XPS";
                case PreviewStringId.RibbonPreview_ShowFirstPage_Caption: return " 첫 번째 페이지";
                case PreviewStringId.RibbonPreview_ShowFirstPage_STipContent: return " 문서의 첫 번째 페이지를 탐색 합니다.";
                case PreviewStringId.RibbonPreview_ShowFirstPage_STipTitle: return " 첫 페이지 (Home)";
                case PreviewStringId.RibbonPreview_ShowLastPage_Caption: return " 마지막 페이지";
                case PreviewStringId.RibbonPreview_ShowLastPage_STipContent: return " 문서의 마지막 페이지로 이동합니다.";
                case PreviewStringId.RibbonPreview_ShowLastPage_STipTitle: return " 마지막 페이지 (End)";
                case PreviewStringId.RibbonPreview_ShowNextPage_Caption: return " 다음 페이지";
                case PreviewStringId.RibbonPreview_ShowNextPage_STipContent: return " 문서의 다음 페이지로 이동 합니다.";
                case PreviewStringId.RibbonPreview_ShowNextPage_STipTitle: return " 다음 페이지 (Right Arrow)";
                case PreviewStringId.RibbonPreview_ShowPrevPage_Caption: return " 이전 페이지";
                case PreviewStringId.RibbonPreview_ShowPrevPage_STipContent: return " 문서의 이전 페이지로 이동 합니다.";
                case PreviewStringId.RibbonPreview_ShowPrevPage_STipTitle: return " 이전 페이지 (Left Arrow)";
                case PreviewStringId.RibbonPreview_Thumbnails_STipContent: return " 열고 축소판, 문서를 탐색할 수 있습니다.";
                case PreviewStringId.RibbonPreview_Watermark_Caption: return " 워터 마크";
                case PreviewStringId.RibbonPreview_Watermark_STipContent: return " 페이지 배경에 워터 마크를 삽입합니다. 일반적으로 특수 처리가 필요하다는 것을 나타내는 경우에 사용합니다.";
                case PreviewStringId.RibbonPreview_Watermark_STipTitle: return " 워터 마크";
                case PreviewStringId.RibbonPreview_Zoom_Caption: return " 확대/축소";
                case PreviewStringId.RibbonPreview_Zoom_STipContent: return " 문서 미리 보기의 확대/축소 수준을 변경 합니다.";
                case PreviewStringId.RibbonPreview_Zoom_STipTitle: return " 확대/축소";
                case PreviewStringId.RibbonPreview_ZoomExact_Caption: return " 정확한:";
                case PreviewStringId.RibbonPreview_ZoomIn_Caption: return " 확대";
                case PreviewStringId.RibbonPreview_ZoomIn_STipContent: return " 문서의 클로 우즈 업 보기를 확대 합니다.";
                case PreviewStringId.RibbonPreview_ZoomIn_STipTitle: return " 확대";
                case PreviewStringId.RibbonPreview_ZoomOut_Caption: return " 축소";
                case PreviewStringId.RibbonPreview_ZoomOut_STipContent: return " 더 많은 감소 된 크기에서 페이지를 볼 축소 합니다.";
                case PreviewStringId.RibbonPreview_ZoomOut_STipTitle: return " 축소";
                case PreviewStringId.SaveDlg_FilterBmp: return " BMP 비트맵 형식";
                case PreviewStringId.SaveDlg_FilterCsv: return " CSV 문서";
                case PreviewStringId.SaveDlg_FilterEmf: return " EMF 향상 된 Windows 메타 파일";
                case PreviewStringId.SaveDlg_FilterGif: return " GIF 그래픽 교환 형식";
                case PreviewStringId.SaveDlg_FilterHtm: return " HTML 문서";
                case PreviewStringId.SaveDlg_FilterJpeg: return " JPEG 파일 교환 형식";
                case PreviewStringId.SaveDlg_FilterMht: return " MHT 문서";
                case PreviewStringId.SaveDlg_FilterNativeFormat: return " 기본 형식";
                case PreviewStringId.SaveDlg_FilterPdf: return " PDF 문서";
                case PreviewStringId.SaveDlg_FilterPng: return " PNG 휴대용 네트워크 그래픽 형식";
                case PreviewStringId.SaveDlg_FilterRtf: return " 서식 있는 텍스트 문서";
                case PreviewStringId.SaveDlg_FilterTiff: return " TIFF 태그 이미지 파일 형식";
                case PreviewStringId.SaveDlg_FilterTxt: return " 텍스트 문서";
                case PreviewStringId.SaveDlg_FilterWmf: return " WMF Windows 메타 파일";
                case PreviewStringId.SaveDlg_FilterXls: return " XLS 문서";
                case PreviewStringId.SaveDlg_FilterXlsx: return " XLSX 문서";
                case PreviewStringId.SaveDlg_FilterXps: return " XPS 문서";
                case PreviewStringId.SaveDlg_Title: return " 다른 이름으로 저장";
                case PreviewStringId.SB_PageInfo: return " {0} / {1}";
                case PreviewStringId.SB_PageNone: return " 없음";
                case PreviewStringId.SB_PageOfPages: return " 페이지 {0} / {1}";
                case PreviewStringId.SB_TTip_Stop: return " 중지";
                case PreviewStringId.SB_ZoomFactor: return " 줌 비율 :";
                case PreviewStringId.ScalePopup_AdjustTo: return " 조정:";
                case PreviewStringId.ScalePopup_NormalSize: return " % 보통 크기";
                case PreviewStringId.ScalePopup_PagesWide: return " 페이지에 맞게 인쇄";
                case PreviewStringId.ScrollingInfo_Page: return " 페이지";
                case PreviewStringId.SignatureCaptions_Date: return " 날짜:";
                case PreviewStringId.SignatureCaptions_Location: return " 위치:";
                case PreviewStringId.TB_TTip_Backgr: return " 배경";
                case PreviewStringId.TB_TTip_Close: return " 미리 보기 닫기";
                case PreviewStringId.TB_TTip_Customize: return " 사용자 지정";
                case PreviewStringId.TB_TTip_EditPageHF: return " 머리글 및 바닥글";
                case PreviewStringId.TB_TTip_Export: return " 문서 내보내기...";
                case PreviewStringId.TB_TTip_FirstPage: return " 첫 페이지";
                case PreviewStringId.TB_TTip_HandTool: return " 손 도구";
                case PreviewStringId.TB_TTip_HighlightEditingFields: return " 편집 필드 강조";
                case PreviewStringId.TB_TTip_LastPage: return " 마지막 페이지";
                case PreviewStringId.TB_TTip_Magnifier: return " 돋보기";
                case PreviewStringId.TB_TTip_Map: return " 문서 구조";
                case PreviewStringId.TB_TTip_MultiplePages: return " 여러 페이지";
                case PreviewStringId.TB_TTip_NextPage: return " 다음 페이지";
                case PreviewStringId.TB_TTip_Open: return " 문서 열기";
                case PreviewStringId.TB_TTip_PageSetup: return " 페이지 설정";
                case PreviewStringId.TB_TTip_Parameters: return " 매개 변수";
                case PreviewStringId.TB_TTip_PreviousPage: return " 이전 페이지";
                case PreviewStringId.TB_TTip_Print: return " 인쇄";
                case PreviewStringId.TB_TTip_PrintDirect: return " 빠른 인쇄";
                case PreviewStringId.TB_TTip_Save: return " 문서 저장";
                case PreviewStringId.TB_TTip_Scale: return " 배율";
                case PreviewStringId.TB_TTip_Search: return " 검색";
                case PreviewStringId.TB_TTip_Send: return " 전자 메일을 통해 보내기...";
                case PreviewStringId.TB_TTip_Watermark: return " 워터 마크";
                case PreviewStringId.TB_TTip_Zoom: return " 확대/축소";
                case PreviewStringId.TB_TTip_ZoomIn: return " 확대";
                case PreviewStringId.TB_TTip_ZoomOut: return " 축소";
                case PreviewStringId.WatermarkTypePicture: return " (사진)";
                case PreviewStringId.WatermarkTypeText: return " (텍스트)";
                case PreviewStringId.WMForm_Direction_BackwardDiagonal: return " 역방향 대각선";
                case PreviewStringId.WMForm_Direction_ForwardDiagonal: return " 정방향 대각선";
                case PreviewStringId.WMForm_Direction_Horizontal: return " 가로";
                case PreviewStringId.WMForm_Direction_Vertical: return " 세로";
                case PreviewStringId.WMForm_HorzAlign_Center: return " 가운데";
                case PreviewStringId.WMForm_HorzAlign_Left: return " 왼쪽";
                case PreviewStringId.WMForm_HorzAlign_Right: return " 오른쪽";
                case PreviewStringId.WMForm_ImageClip: return " 클립";
                case PreviewStringId.WMForm_ImageStretch: return " 스트레치";
                case PreviewStringId.WMForm_ImageZoom: return " 확대/축소";
                case PreviewStringId.WMForm_PictureDlg_Title: return " 그림 선택";
                case PreviewStringId.WMForm_VertAlign_Bottom: return " 하단";
                case PreviewStringId.WMForm_VertAlign_Middle: return " 중간";
                case PreviewStringId.WMForm_VertAlign_Top: return " 상단";
                case PreviewStringId.WMForm_Watermark_Asap: return " 최대한 빨리";
                case PreviewStringId.WMForm_Watermark_Confidential: return " 기밀";
                case PreviewStringId.WMForm_Watermark_Copy: return " 복사";
                case PreviewStringId.WMForm_Watermark_DoNotCopy: return " 복사 금지";
                case PreviewStringId.WMForm_Watermark_Draft: return " 초안";
                case PreviewStringId.WMForm_Watermark_Evaluation: return " 평가판";
                case PreviewStringId.WMForm_Watermark_Original: return " 원본";
                case PreviewStringId.WMForm_Watermark_Personal: return " 개인";
                case PreviewStringId.WMForm_Watermark_Sample: return " 샘플";
                case PreviewStringId.WMForm_Watermark_TopSecret: return " 일급 비밀";
                case PreviewStringId.WMForm_Watermark_Urgent: return " 긴급";
                case PreviewStringId.RibbonPreview_Thumbnails_Caption: return " 축소판";
            }
            return base.GetLocalizedString(id);
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="id"></param>
        ///// <returns></returns>
        //public override string GetLocalizedString(PreviewStringId id)
        //{
        //    switch (id)
        //    {
        //        case PreviewStringId.RibbonPreview_ShowNextPage_Caption:
        //            return "다음";
        //        case PreviewStringId.RibbonPreview_ShowPrevPage_Caption:
        //            return "이전";
        //        case PreviewStringId.RibbonPreview_ShowLastPage_Caption:
        //            return "마지막";
        //        case PreviewStringId.RibbonPreview_ShowFirstPage_Caption:
        //            return "처음";
        //        case PreviewStringId.RibbonPreview_ClosePreview_Caption:
        //            return "닫기";
        //        case PreviewStringId.RibbonPreview_Customize_Caption:
        //            return "설정";
        //        case PreviewStringId.RibbonPreview_Open_Caption:
        //            return "열기";
        //        case PreviewStringId.RibbonPreview_Save_Caption:
        //            return "저장";
        //        case PreviewStringId.RibbonPreview_Parameters_Caption:
        //            return "파라미터";
        //        case PreviewStringId.RibbonPreview_EditPageHF_Caption:
        //            return "머리글/바닥글";
        //        case PreviewStringId.RibbonPreview_Scale_Caption:
        //            return "배율";
        //        case PreviewStringId.RibbonPreview_PageOrientation_Caption:
        //            return "방향";
        //        case PreviewStringId.RibbonPreview_PageMargins_Caption:
        //            return "여백";
        //        case PreviewStringId.RibbonPreview_PaperSize_Caption:
        //            return "크기";
        //        case PreviewStringId.RibbonPreview_Thumbnails_Caption:
        //            return "썸네일";
        //        case PreviewStringId.RibbonPreview_Find_Caption:
        //            return "찾기";
        //        case PreviewStringId.RibbonPreview_Print_Caption:
        //            return "인쇄";
        //        case PreviewStringId.RibbonPreview_PrintDirect_Caption:
        //            return "빠른 인쇄";
        //    }
        //    return base.GetLocalizedString(id);
        //}
    }
}
