using DevExpress.XtraRichEdit.Localization;

namespace EBAP.Win.BaseFrame.Localization
{
    /// <summary>
    /// Rich Edit Control Library를 한국어로 설정합니다.
    /// </summary>
    internal class PRichEditLocalizer : DevExpress.XtraRichEdit.Localization.XtraRichEditLocalizer
    {
        /// <summary>
        /// Editor Control에서 보여지는 Text를 설정합니다.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public override string GetLocalizedString(XtraRichEditStringId id)
        {
            switch (id)
            {
                case XtraRichEditStringId.BorderLineStyleNone: return " 없음";
                case XtraRichEditStringId.Caption_AlignmentCenter: return " 중앙";
                case XtraRichEditStringId.Caption_AlignmentJustify: return " 양쪽 맞춤";
                case XtraRichEditStringId.Caption_AlignmentLeft: return " 왼쪽";
                case XtraRichEditStringId.Caption_AlignmentRight: return " 오른쪽";
                case XtraRichEditStringId.Caption_CaptionPrefixEquation: return " 방정식";
                case XtraRichEditStringId.Caption_CaptionPrefixFigure: return " 그림";
                case XtraRichEditStringId.Caption_CaptionPrefixTable: return " 테이블";
                case XtraRichEditStringId.Caption_CharacterPositionNormal: return " 보통";
                case XtraRichEditStringId.Caption_CharacterSpacingNormal: return " 보통";
                case XtraRichEditStringId.Caption_ClipboardSubItem: return " 클립보드";
                case XtraRichEditStringId.Caption_ColorAutomatic: return " 자동";
                case XtraRichEditStringId.Caption_CurrentDocumentHyperlinkTooltip: return " 현재 문서";
                case XtraRichEditStringId.Caption_CurrentParagraphText: return " 샘플 텍스트";
                case XtraRichEditStringId.Caption_CustomPropertyGroup: return " 그룹";
                case XtraRichEditStringId.Caption_CustomPropertyNo: return " 아니오";
                case XtraRichEditStringId.Caption_CustomPropertyStatus: return " 상태";
                case XtraRichEditStringId.Caption_CustomPropertyTypeDateTime: return " 날짜";
                case XtraRichEditStringId.Caption_CustomPropertyTypeNumber: return " 숫자";
                case XtraRichEditStringId.Caption_CustomPropertyTypeText: return " 텍스트";
                case XtraRichEditStringId.Caption_CustomPropertyValue: return " 값";
                case XtraRichEditStringId.Caption_CustomPropertyYes: return " 예";
                case XtraRichEditStringId.Caption_EvenPageFooter: return " 짝수 페이지 바닥글";
                case XtraRichEditStringId.Caption_EvenPageHeader: return " 짝수 페이지 머리글";
                case XtraRichEditStringId.Caption_FirstLineIndentIndented: return " 첫 번째 줄";
                case XtraRichEditStringId.Caption_FirstLineIndentNone: return " (없음)";
                case XtraRichEditStringId.Caption_FirstPageFooter: return " 첫 페이지 바닥글";
                case XtraRichEditStringId.Caption_FirstPageHeader: return " 첫 페이지 머리글";
                case XtraRichEditStringId.Caption_FollowingParagraphText: return " 다음 단락";
                case XtraRichEditStringId.Caption_GroupTableAlignment: return " 맞춤";
                case XtraRichEditStringId.Caption_GroupTableStyleOptions: return " 표 스타일 옵션";
                case XtraRichEditStringId.Caption_GroupTableTable: return " 테이블";
                case XtraRichEditStringId.Caption_HeightTypeMinimum: return " 최소";
                case XtraRichEditStringId.Caption_LineSpacingAtLeast: return " 최소";
                case XtraRichEditStringId.Caption_NoColor: return " 색 없음";
                case XtraRichEditStringId.Caption_NumberingListBoxNone: return " 없음";
                case XtraRichEditStringId.Caption_OddPageFooter: return " 홀수 페이지 바닥글";
                case XtraRichEditStringId.Caption_OddPageHeader: return " 홀수 페이지 머리글";
                case XtraRichEditStringId.Caption_OutlineLevel1: return " 레벨 1";
                case XtraRichEditStringId.Caption_OutlineLevel2: return " 레벨 2";
                case XtraRichEditStringId.Caption_OutlineLevel3: return " 레벨 3";
                case XtraRichEditStringId.Caption_OutlineLevel4: return " 레벨 4";
                case XtraRichEditStringId.Caption_OutlineLevel5: return " 레벨 5";
                case XtraRichEditStringId.Caption_OutlineLevel6: return " 레벨 6";
                case XtraRichEditStringId.Caption_OutlineLevel7: return " 레벨 7";
                case XtraRichEditStringId.Caption_OutlineLevel8: return " 레벨 8";
                case XtraRichEditStringId.Caption_OutlineLevel9: return " 레벨 9";
                case XtraRichEditStringId.Caption_OutlineLevelBody: return " 본문";
                case XtraRichEditStringId.Caption_PageBreak: return " 페이지 나누기";
                case XtraRichEditStringId.Caption_PageFooter: return " 바닥글";
                case XtraRichEditStringId.Caption_PageHeader: return " 헤더";
                case XtraRichEditStringId.Caption_PageSetupSectionStartColumn: return " 새 열";
                case XtraRichEditStringId.Caption_PageSetupSectionStartContinuous: return " 연속";
                case XtraRichEditStringId.Caption_PageSetupSectionStartEvenPage: return " 짝수 페이지";
                case XtraRichEditStringId.Caption_PageSetupSectionStartNextPage: return " 새 페이지";
                case XtraRichEditStringId.Caption_PageSetupSectionStartOddPage: return " 홀수 페이지";
                case XtraRichEditStringId.Caption_PageTableDesign: return " 디자인";
                case XtraRichEditStringId.Caption_PageTableLayout: return " 레이아웃";
                case XtraRichEditStringId.Caption_ParagraphAlignment_Center: return " 가운데";
                case XtraRichEditStringId.Caption_ParagraphAlignment_Justify: return " 양쪽 맞춤";
                case XtraRichEditStringId.Caption_ParagraphAlignment_Left: return " 왼쪽";
                case XtraRichEditStringId.Caption_ParagraphAlignment_Right: return " 오른쪽";
                case XtraRichEditStringId.Caption_ParagraphFirstLineIndent_Indented: return " 들여쓰기";
                case XtraRichEditStringId.Caption_ParagraphFirstLineIndent_None: return " 없음";
                case XtraRichEditStringId.Caption_ParagraphLineSpacing_AtLeast: return " 최소";
                case XtraRichEditStringId.Caption_PreviousParagraphText: return " 이전 단락";
                case XtraRichEditStringId.Caption_SameAsPrevious: return " 이전과 동일";
                case XtraRichEditStringId.Caption_SectionBreakTypeColumn: return " 열";
                case XtraRichEditStringId.Caption_SectionBreakTypeNextPage: return " 다음 페이지";
                case XtraRichEditStringId.Caption_SectionPropertiesApplyThisPointForward: return " 이 부분 이상";
                case XtraRichEditStringId.Caption_SectionPropertiesApplyToCurrentSection: return " 현재 섹션";
                case XtraRichEditStringId.Caption_SectionPropertiesApplyToSelectedSections: return " 선택한 섹션";
                case XtraRichEditStringId.Caption_SectionPropertiesApplyToWholeDocument: return " 전체 문서";
                case XtraRichEditStringId.Caption_WatermarkFontSizeAuto: return " 자동";
                case XtraRichEditStringId.Caption_WatermarkPictureScale100p: return " 1";
                case XtraRichEditStringId.Caption_WatermarkPictureScaleAuto: return " 자동";
                case XtraRichEditStringId.ClearFormatting: return " 서식 지우기";
                case XtraRichEditStringId.ColorAuto: return " 자동";
                case XtraRichEditStringId.DefaultDocumentName: return " 문서";
                case XtraRichEditStringId.DefaultStyleName_annotationreference: return " 참고 주석";
                case XtraRichEditStringId.DefaultStyleName_annotationsubject: return " 주석 제목";
                case XtraRichEditStringId.DefaultStyleName_annotationtext: return " 주석 텍스트";
                case XtraRichEditStringId.DefaultStyleName_BalloonText: return " 풍선 텍스트";
                case XtraRichEditStringId.DefaultStyleName_BlockText: return " 텍스트 블록";
                case XtraRichEditStringId.DefaultStyleName_BodyText: return " 본문";
                case XtraRichEditStringId.DefaultStyleName_BodyText2: return " 본문 2";
                case XtraRichEditStringId.DefaultStyleName_BodyText3: return " 본문 3";
                case XtraRichEditStringId.DefaultStyleName_BodyTextFirstIndent: return " 본문 첫 번째 들여 쓰기";
                case XtraRichEditStringId.DefaultStyleName_BodyTextFirstIndent2: return " 본문 첫 번째 들여 쓰기 2";
                case XtraRichEditStringId.DefaultStyleName_BodyTextIndent2: return " 본문 들여 쓰기 2";
                case XtraRichEditStringId.DefaultStyleName_BodyTextIndent3: return " 본문 들여 쓰기 3";
                case XtraRichEditStringId.DefaultStyleName_caption: return " 캡션";
                case XtraRichEditStringId.DefaultStyleName_Closing: return " 닫기";
                case XtraRichEditStringId.DefaultStyleName_CommentReference: return " 댓글 참조";
                case XtraRichEditStringId.DefaultStyleName_Date: return " 날짜";
                case XtraRichEditStringId.DefaultStyleName_DefaultParagraphFont: return " 기본 단락 글꼴";
                case XtraRichEditStringId.DefaultStyleName_DocumentMap: return " 문서 구조";
                case XtraRichEditStringId.DefaultStyleName_EmailSignature: return " 전자 메일 서명";
                case XtraRichEditStringId.DefaultStyleName_Emphasis: return " 강조";
                case XtraRichEditStringId.DefaultStyleName_endnotereference: return " 참고 문헌";
                case XtraRichEditStringId.DefaultStyleName_endnotetext: return " 참고 문헌 텍스트";
                case XtraRichEditStringId.DefaultStyleName_envelopeaddress: return " 봉투 주소";
                case XtraRichEditStringId.DefaultStyleName_footer: return " 바닥글";
                case XtraRichEditStringId.DefaultStyleName_footnotereference: return " 각주 참조";
                case XtraRichEditStringId.DefaultStyleName_footnotetext: return " 각주 텍스트";
                case XtraRichEditStringId.DefaultStyleName_header: return " 헤더";
                case XtraRichEditStringId.DefaultStyleName_heading1: return " 제목 1";
                case XtraRichEditStringId.DefaultStyleName_heading2: return " 제목 2";
                case XtraRichEditStringId.DefaultStyleName_heading3: return " 제목 3";
                case XtraRichEditStringId.DefaultStyleName_heading4: return " 제목 4";
                case XtraRichEditStringId.DefaultStyleName_heading5: return " 제목 5";
                case XtraRichEditStringId.DefaultStyleName_heading6: return " 제목 6";
                case XtraRichEditStringId.DefaultStyleName_heading7: return " 제목 7";
                case XtraRichEditStringId.DefaultStyleName_heading8: return " 제목 8";
                case XtraRichEditStringId.DefaultStyleName_heading9: return " 제목 9";
                case XtraRichEditStringId.DefaultStyleName_HTMLAcronym: return " HTML 약어";
                case XtraRichEditStringId.DefaultStyleName_HTMLAddress: return " HTML 주소";
                case XtraRichEditStringId.DefaultStyleName_HTMLBottomofForm: return " HTML 폼의 하단";
                case XtraRichEditStringId.DefaultStyleName_HTMLCite: return " HTML 인용";
                case XtraRichEditStringId.DefaultStyleName_HTMLCode: return " HTML 코드";
                case XtraRichEditStringId.DefaultStyleName_HTMLDefinition: return " HTML 정의";
                case XtraRichEditStringId.DefaultStyleName_HTMLKeyboard: return " HTML 키보드";
                case XtraRichEditStringId.DefaultStyleName_HTMLSample: return " HTML 샘플";
                case XtraRichEditStringId.DefaultStyleName_HTMLTypewriter: return " HTML 타자기";
                case XtraRichEditStringId.DefaultStyleName_HTMLVariable: return " HTML 변수";
                case XtraRichEditStringId.DefaultStyleName_HyperlinkFollowed: return " HyperlinkFollowed";
                case XtraRichEditStringId.DefaultStyleName_HyperlinkStrongEmphasis: return " HyperlinkStrongEmphasis";
                case XtraRichEditStringId.DefaultStyleName_index1: return " 색인 1";
                case XtraRichEditStringId.DefaultStyleName_index2: return " 색인 2";
                case XtraRichEditStringId.DefaultStyleName_index3: return " 색인 3";
                case XtraRichEditStringId.DefaultStyleName_index4: return " 색인 4";
                case XtraRichEditStringId.DefaultStyleName_index5: return " 색인 5";
                case XtraRichEditStringId.DefaultStyleName_index6: return " 색인 6";
                case XtraRichEditStringId.DefaultStyleName_index7: return " 색인 7";
                case XtraRichEditStringId.DefaultStyleName_index8: return " 색인 8";
                case XtraRichEditStringId.DefaultStyleName_index9: return " 색인 9";
                case XtraRichEditStringId.DefaultStyleName_indexheading: return " 색인 제목";
                case XtraRichEditStringId.DefaultStyleName_linenumber: return " 줄 번호";
                case XtraRichEditStringId.DefaultStyleName_List: return " 목록";
                case XtraRichEditStringId.DefaultStyleName_List2: return " 목록 2";
                case XtraRichEditStringId.DefaultStyleName_List3: return " 목록 3";
                case XtraRichEditStringId.DefaultStyleName_List4: return " 목록 4";
                case XtraRichEditStringId.DefaultStyleName_List5: return " 목록 5";
                case XtraRichEditStringId.DefaultStyleName_ListBullet: return " 글 머리 기호 목록";
                case XtraRichEditStringId.DefaultStyleName_ListBullet2: return " 글 머리 기호 목록 2";
                case XtraRichEditStringId.DefaultStyleName_ListBullet3: return " 글 머리 기호 목록 3";
                case XtraRichEditStringId.DefaultStyleName_ListBullet4: return " 글 머리 기호 목록 4";
                case XtraRichEditStringId.DefaultStyleName_ListBullet5: return " 글 머리 기호 목록 5";
                case XtraRichEditStringId.DefaultStyleName_ListContinue: return " 목록 계속";
                case XtraRichEditStringId.DefaultStyleName_ListContinue2: return " 목록 계속 2";
                case XtraRichEditStringId.DefaultStyleName_ListContinue3: return " 목록 계속 3";
                case XtraRichEditStringId.DefaultStyleName_ListContinue4: return " 목록 계속 4";
                case XtraRichEditStringId.DefaultStyleName_ListContinue5: return " 목록 계속 5";
                case XtraRichEditStringId.DefaultStyleName_ListNumber: return " 목록 번호";
                case XtraRichEditStringId.DefaultStyleName_ListNumber2: return " 목록 번호 2";
                case XtraRichEditStringId.DefaultStyleName_ListNumber3: return " 목록 번호 3";
                case XtraRichEditStringId.DefaultStyleName_ListNumber4: return " 목록 번호 4";
                case XtraRichEditStringId.DefaultStyleName_ListNumber5: return " 목록 번호 5";
                case XtraRichEditStringId.DefaultStyleName_MacroText: return " 매크로 텍스트";
                case XtraRichEditStringId.DefaultStyleName_macrotoaheading: return " 표제에 매크로";
                case XtraRichEditStringId.DefaultStyleName_MessageHeader: return " 메시지 머리글";
                case XtraRichEditStringId.DefaultStyleName_NoList: return " 목록 없음";
                case XtraRichEditStringId.DefaultStyleName_Normal: return " 표준";
                case XtraRichEditStringId.DefaultStyleName_NormalIndent: return " 표준 들여쓰기";
                case XtraRichEditStringId.DefaultStyleName_NormalTable: return " 표준 테이블";
                case XtraRichEditStringId.DefaultStyleName_NormalWeb: return " 표준 (Web)";
                case XtraRichEditStringId.DefaultStyleName_NoteHeading: return " 참고 제목";
                case XtraRichEditStringId.DefaultStyleName_OutlineList1: return " 개요 목록 1";
                case XtraRichEditStringId.DefaultStyleName_OutlineList2: return " 개요 목록 2";
                case XtraRichEditStringId.DefaultStyleName_OutlineList3: return " 개요 목록 3";
                case XtraRichEditStringId.DefaultStyleName_pagenumber: return " 페이지 번호";
                case XtraRichEditStringId.DefaultStyleName_PlainText: return " 일반 텍스트";
                case XtraRichEditStringId.DefaultStyleName_Salutation: return " 인사말";
                case XtraRichEditStringId.DefaultStyleName_Signature: return " 서명";
                case XtraRichEditStringId.DefaultStyleName_Subtitle: return " 자막";
                case XtraRichEditStringId.DefaultStyleName_Table3Deffects1: return " 테이블 3D 효과 1";
                case XtraRichEditStringId.DefaultStyleName_Table3Deffects2: return " 테이블 3D 효과 2";
                case XtraRichEditStringId.DefaultStyleName_Table3Deffects3: return " 테이블 3D 효과 3";
                case XtraRichEditStringId.DefaultStyleName_TableClassic1: return " 테이블 클래식 1";
                case XtraRichEditStringId.DefaultStyleName_TableClassic2: return " 테이블 클래식 2";
                case XtraRichEditStringId.DefaultStyleName_TableClassic3: return " 테이블 클래식 3";
                case XtraRichEditStringId.DefaultStyleName_TableClassic4: return " 테이블 클래식 4";
                case XtraRichEditStringId.DefaultStyleName_TableColorful1: return " 표 다채로운 1";
                case XtraRichEditStringId.DefaultStyleName_TableColorful2: return " 표 다채로운 2";
                case XtraRichEditStringId.DefaultStyleName_TableColorful3: return " 표 다채로운 3";
                case XtraRichEditStringId.DefaultStyleName_TableColumns1: return " 테이블 열 1";
                case XtraRichEditStringId.DefaultStyleName_TableColumns2: return " 테이블 열 2";
                case XtraRichEditStringId.DefaultStyleName_TableColumns3: return " 테이블 열 3";
                case XtraRichEditStringId.DefaultStyleName_TableColumns4: return " 테이블 열 4";
                case XtraRichEditStringId.DefaultStyleName_TableColumns5: return " 테이블 열 5";
                case XtraRichEditStringId.DefaultStyleName_TableElegant: return " 우아한 테이블";
                case XtraRichEditStringId.DefaultStyleName_TableGrid: return " 테이블 표";
                case XtraRichEditStringId.DefaultStyleName_TableGrid1: return " 테이블 표 1";
                case XtraRichEditStringId.DefaultStyleName_TableGrid2: return " 테이블 표 2";
                case XtraRichEditStringId.DefaultStyleName_TableGrid3: return " 테이블 표 3";
                case XtraRichEditStringId.DefaultStyleName_TableGrid4: return " 테이블 표 4";
                case XtraRichEditStringId.DefaultStyleName_TableGrid5: return " 테이블 표 5";
                case XtraRichEditStringId.DefaultStyleName_TableGrid6: return " 테이블 표 6";
                case XtraRichEditStringId.DefaultStyleName_TableGrid7: return " 테이블 표 7";
                case XtraRichEditStringId.DefaultStyleName_TableGrid8: return " 테이블 표 8";
                case XtraRichEditStringId.DefaultStyleName_TableList1: return " 테이블 목록 1";
                case XtraRichEditStringId.DefaultStyleName_TableList2: return " 테이블 목록 2";
                case XtraRichEditStringId.DefaultStyleName_TableList3: return " 테이블 목록 3";
                case XtraRichEditStringId.DefaultStyleName_TableList4: return " 테이블 목록 4";
                case XtraRichEditStringId.DefaultStyleName_TableList5: return " 테이블 목록 5";
                case XtraRichEditStringId.DefaultStyleName_TableList6: return " 테이블 목록 6";
                case XtraRichEditStringId.DefaultStyleName_TableList7: return " 테이블 목록 7";
                case XtraRichEditStringId.DefaultStyleName_TableList8: return " 테이블 목록 8";
                case XtraRichEditStringId.DefaultStyleName_tableofauthorities: return " 참고 문헌 테이블";
                case XtraRichEditStringId.DefaultStyleName_tableoffigures: return " 그림 테이블";
                case XtraRichEditStringId.DefaultStyleName_TableProfessional: return " 테이블 전문가";
                case XtraRichEditStringId.DefaultStyleName_TableSimple1: return " 테이블 심플 1";
                case XtraRichEditStringId.DefaultStyleName_TableSimple2: return " 테이블 심플 2";
                case XtraRichEditStringId.DefaultStyleName_TableSimple3: return " 테이블 심플 3";
                case XtraRichEditStringId.DefaultStyleName_TableSubtle1: return " 테이블 미세 1";
                case XtraRichEditStringId.DefaultStyleName_TableSubtle2: return " 테이블 미세 2";
                case XtraRichEditStringId.DefaultStyleName_TableTheme: return " 테이블 테마";
                case XtraRichEditStringId.DefaultStyleName_TableWeb1: return " 테이블 Web 1";
                case XtraRichEditStringId.DefaultStyleName_TableWeb2: return " 테이블 Web 2";
                case XtraRichEditStringId.DefaultStyleName_TableWeb3: return " 테이블 Web 3";
                case XtraRichEditStringId.DefaultStyleName_Title: return " 제목";
                case XtraRichEditStringId.DefaultStyleName_toaheading: return " TOA 제목";
                case XtraRichEditStringId.DefaultStyleName_toc1: return " 목차 1";
                case XtraRichEditStringId.DefaultStyleName_toc2: return " 목차 2";
                case XtraRichEditStringId.DefaultStyleName_toc3: return " 목차 3";
                case XtraRichEditStringId.DefaultStyleName_toc4: return " 목차 4";
                case XtraRichEditStringId.DefaultStyleName_toc5: return " 목차 5";
                case XtraRichEditStringId.DefaultStyleName_toc6: return " 목차 6";
                case XtraRichEditStringId.DefaultStyleName_toc7: return " 목차 7";
                case XtraRichEditStringId.DefaultStyleName_toc8: return " 목차 8";
                case XtraRichEditStringId.DefaultStyleName_toc9: return " 목차 9";
                case XtraRichEditStringId.DialogCaption_InsertSymbol: return " 기호";
                case XtraRichEditStringId.FieldLastName: return " 이름 (성)";
                case XtraRichEditStringId.FieldMapAddress1: return " 주소 1";
                case XtraRichEditStringId.FieldMapAddress2: return " 주소 2";
                case XtraRichEditStringId.FieldMapAddress3: return " 주소 3";
                case XtraRichEditStringId.FieldMapBusinessFax: return " FAX 번호 (회사)";
                case XtraRichEditStringId.FieldMapBusinessPhone: return " 전화 번호 (회사)";
                case XtraRichEditStringId.FieldMapCountry: return " 국가 또는 지역";
                case XtraRichEditStringId.FieldMapDepartment: return " 부서";
                case XtraRichEditStringId.FieldMapEMailAddress: return " 전자 메일 주소";
                case XtraRichEditStringId.FieldMapFirstName: return " 이름";
                case XtraRichEditStringId.FieldMapHomeFax: return " FAX 번호 (자택)";
                case XtraRichEditStringId.FieldMapHomePhone: return " 전화 번호 (자택)";
                case XtraRichEditStringId.FieldMapJobTitle: return " 직함";
                case XtraRichEditStringId.FieldMapMiddleName: return " 중간 이름";
                case XtraRichEditStringId.FieldMapNickName: return " 닉네임";
                case XtraRichEditStringId.FieldMapPostalCode: return " 우편 번호";
                case XtraRichEditStringId.FieldMapSuffix: return " 접미사";
                case XtraRichEditStringId.FieldMapTitle: return " 경칭";
                case XtraRichEditStringId.FieldMapWebPage: return " 웹 페이지";
                case XtraRichEditStringId.FileFilterDescription_AllFiles: return " 모든 파일";
                case XtraRichEditStringId.FileFilterDescription_BitmapFiles: return " 비트맵";
                case XtraRichEditStringId.FileFilterDescription_DocFiles: return " Microsoft Word 문서";
                case XtraRichEditStringId.FileFilterDescription_ePubFiles: return " 전자 출판물";
                case XtraRichEditStringId.FileFilterDescription_GifFiles: return " GIF 형식";
                case XtraRichEditStringId.FileFilterDescription_HtmlFiles: return " HTML 형식";
                case XtraRichEditStringId.FileFilterDescription_JPEGFiles: return " JPEG 파일 교환 형식";
                case XtraRichEditStringId.FileFilterDescription_MhtFiles: return " 단일 파일 Web 아카이브";
                case XtraRichEditStringId.FileFilterDescription_OpenDocumentFiles: return " OpenDocument 텍스트 형식";
                case XtraRichEditStringId.FileFilterDescription_OpenXmlFiles: return " Word 문서";
                case XtraRichEditStringId.FileFilterDescription_PDFFiles: return " 휴대용 문서 형식 (PDF)";
                case XtraRichEditStringId.FileFilterDescription_TextFiles: return " 텍스트 파일";
                case XtraRichEditStringId.FileFilterDescription_TiffFiles: return " TIFF 형식";
                case XtraRichEditStringId.FileFilterDescription_WordMLFiles: return " XML 문서";
                case XtraRichEditStringId.FileFilterDescription_XamlFiles: return " Xaml 문서";
                case XtraRichEditStringId.FindAndReplaceForm_AnySingleCharacter: return " 모든 단일 문자";
                case XtraRichEditStringId.FindAndReplaceForm_BeginningOfLine: return " 단락 시작";
                case XtraRichEditStringId.FindAndReplaceForm_BeginningOfWord: return " 단어의 시작";
                case XtraRichEditStringId.FindAndReplaceForm_EndOfLine: return " 단락 끝";
                case XtraRichEditStringId.FindAndReplaceForm_EndOfWord: return " 단어의 끝";
                case XtraRichEditStringId.FindAndReplaceForm_EscapeSpecialCharacter: return " 이스케이프 문자";
                case XtraRichEditStringId.FindAndReplaceForm_Integer: return " 정수";
                case XtraRichEditStringId.FindAndReplaceForm_OneOrMore: return " 하나 이상";
                case XtraRichEditStringId.FindAndReplaceForm_Or: return " 또는";
                case XtraRichEditStringId.FindAndReplaceForm_SpaceOrTab: return " 공백 또는 탭";
                case XtraRichEditStringId.FindAndReplaceForm_TagExpression: return " 태그 표기";
                case XtraRichEditStringId.FindAndReplaceForm_TaggedExpression: return " 태그 표기 {0}";
                case XtraRichEditStringId.FindAndReplaceForm_WordCharacter: return " 문자";
                case XtraRichEditStringId.FindAndReplaceForm_ZeroOrMore: return " 0 이상";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionAlignmentCenter: return " 중앙";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionAlignmentLeft: return " 왼쪽";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionAlignmentRight: return " 오른쪽";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypeCharacter: return " 문자";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypeColumn: return " 열";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypeInsideMargin: return " 안쪽 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypeLeftMargin: return " 왼쪽 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypeMargin: return " 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypePage: return " 페이지";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_HorizontalPositionTypeRightMargin: return " 오른쪽 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionAlignmentBottom: return " 하단";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionAlignmentCenter: return " 중앙";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionAlignmentInside: return " 내부";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionAlignmentOutside: return " 외부";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionAlignmentTop: return " 상단";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypeBottomMargin: return " 아래쪽 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypeInsideMargin: return " 안쪽 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypeLine: return " 라인";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypeMargin: return " 여백";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypePage: return " 페이지";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypeParagraph: return " 단락";
                case XtraRichEditStringId.FloatingObjectLayoutOptionsForm_VerticalPositionTypeTopMargin: return " 위쪽 여백";
                case XtraRichEditStringId.FontStyle_Bold: return " 굵게";
                case XtraRichEditStringId.FontStyle_BoldItalic: return " 굵게 기울임꼴";
                case XtraRichEditStringId.FontStyle_Italic: return " 기울임꼴";
                case XtraRichEditStringId.FontStyle_Regular: return " 일반";
                case XtraRichEditStringId.FontStyle_Strikeout: return " 취소선";
                case XtraRichEditStringId.FontStyle_Underline: return " 밑줄";
                case XtraRichEditStringId.HyperlinkForm_EditHyperlinkTitle: return " 하이퍼링크 편집";
                case XtraRichEditStringId.HyperlinkForm_InsertHyperlinkTitle: return " 하이퍼링크 삽입";
                case XtraRichEditStringId.HyperlinkForm_SelectedBookmarkNone: return " < 없음 >";
                case XtraRichEditStringId.HyperlinkForm_SelectionInDocument: return " 문서에서 선택";
                case XtraRichEditStringId.LocalizedStyleName_Hyperlink: return " 하이퍼링크";
                case XtraRichEditStringId.LocalizedStyleName_Normal: return " 표준";
                case XtraRichEditStringId.MenuCmd_AddParagraphsToTableOfContents: return " 텍스트 추가";
                case XtraRichEditStringId.MenuCmd_AddWordToDictionary: return " 사전에 추가";
                case XtraRichEditStringId.MenuCmd_AddWordToDictionaryDescription: return " 사전에 추가";
                case XtraRichEditStringId.MenuCmd_BackSpaceKey: return " BackSpaceKey";
                case XtraRichEditStringId.MenuCmd_BackSpaceKeyDescription: return " BackSpaceKey";
                case XtraRichEditStringId.MenuCmd_Bookmark: return " 책갈피...";
                case XtraRichEditStringId.MenuCmd_BookmarkDescription: return " 책갈피...";
                case XtraRichEditStringId.MenuCmd_BrowserPrint: return " 브라우저 인쇄";
                case XtraRichEditStringId.MenuCmd_BrowserPrintPreview: return " 브라우저 인쇄 미리 보기";
                case XtraRichEditStringId.MenuCmd_BrowserPrintPreviewDescription: return " 인쇄 하기 전에 브라우저에서 페이지를 미리 보기 합니다.";
                case XtraRichEditStringId.MenuCmd_CapitalizeEachWordTextCase: return " 각 단어를 대문자로";
                case XtraRichEditStringId.MenuCmd_CapitalizeEachWordTextCaseDescription: return " 각 단어를 대문자로.";
                case XtraRichEditStringId.MenuCmd_ChangeColumnCount: return " 열";
                case XtraRichEditStringId.MenuCmd_ChangeColumnCountDescription: return " 열";
                case XtraRichEditStringId.MenuCmd_ChangeCurrentBorderRepositoryItemColor: return " 펜 색";
                case XtraRichEditStringId.MenuCmd_ChangeCurrentBorderRepositoryItemColorDescription: return " 펜 색을 변경 합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeCurrentBorderRepositoryItemLineStyle: return " 테두리 스타일";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectAlignment: return " 위치";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectFillColor: return " 도형 채우기";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectFillColorDescription: return " 선택된 도형을 단색으로 채웁니다.";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectOutlineColor: return " 도형 윤곽선";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectOutlineColorDescription: return " 선택된 도형의 윤곽선 색을 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectTextWrapType: return " 텍스트 줄 바꿈";
                case XtraRichEditStringId.MenuCmd_ChangeFloatingObjectTextWrapTypeDescription: return " 선택된 개체에 대한 텍스트 배치 방법을 변경합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeFontColor: return " 글꼴 색";
                case XtraRichEditStringId.MenuCmd_ChangeFontColorDescription: return " 글꼴 색을 변경 합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeFontName: return " 글꼴";
                case XtraRichEditStringId.MenuCmd_ChangeFontSize: return " 글꼴 크기";
                case XtraRichEditStringId.MenuCmd_ChangeFontSizeDescription: return " 글꼴 크기를 변경 합니다.";
                case XtraRichEditStringId.MenuCmd_ChangePageColor: return " 페이지 색상";
                case XtraRichEditStringId.MenuCmd_ChangePageColorDescription: return " 페이지의 배경에 대 한 색을 선택 합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphBackColor: return " 음영";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphBackColorDescription: return " 선택한 단락 뒤에 배경을 변경 합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphLineSpacing: return " 줄 간격";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphLineSpacingDescription: return " 변경 텍스트 줄 사이의 간격입니다. 또한 추가 단락 앞뒤 간격을 사용자 지정할 수 있습니다.";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphStyle: return " ChangeParagraphStyle";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphStyleDescription: return " ChangeParagraphStyle";
                case XtraRichEditStringId.MenuCmd_ChangeSectionLineNumbering: return " 줄 번호 ";
                case XtraRichEditStringId.MenuCmd_ChangeSectionLineNumberingDescription: return " 문서의 각 행 옆의 여백에 줄 번호를 추가합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeSectionPageMargins: return " 여백";
                case XtraRichEditStringId.MenuCmd_ChangeSectionPageMarginsDescription: return " 전체 문서 또는 현재 섹션의 여백 크기를 선택합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeSectionPageOrientation: return " 페이지 방향";
                case XtraRichEditStringId.MenuCmd_ChangeSectionPageOrientationDescription: return " 세로와 가로 레이아웃을 전환합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeSectionPagePaperKind: return " 크기";
                case XtraRichEditStringId.MenuCmd_ChangeSectionPagePaperKindDescription: return " 현재 섹션의 용지 크기를 선택합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeStyle: return " 빠른 스타일";
                case XtraRichEditStringId.MenuCmd_ChangeTableBorders: return " 테두리";
                case XtraRichEditStringId.MenuCmd_ChangeTableBordersDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeTableCellAlignmentPlaceholder: return " 맞춤";
                case XtraRichEditStringId.MenuCmd_ChangeTableCellsContentAlignment: return " 셀 맞춤";
                case XtraRichEditStringId.MenuCmd_ChangeTableCellsContentAlignmentDescription: return " 셀 맞춤";
                case XtraRichEditStringId.MenuCmd_ChangeTableCellShading: return " 음영";
                case XtraRichEditStringId.MenuCmd_ChangeTableCellShadingDescription: return " 선택한 셀의 배경색을 변경합니다.";
                case XtraRichEditStringId.MenuCmd_ChangeTableCellsTextDirectionHorizontalContextMenuItem: return " 가로";
                case XtraRichEditStringId.MenuCmd_CheckSpelling: return " 맞춤법 검사";
                case XtraRichEditStringId.MenuCmd_CheckSpellingDescription: return " 문서에서 텍스트의 맞춤법을 검사합니다.";
                case XtraRichEditStringId.MenuCmd_ClearFormatting: return " 서식 지우기";
                case XtraRichEditStringId.MenuCmd_ClearFormattingDescription: return " 떠나만 일반 텍스트 선택 영역에서 모든 서식 선택을 취소 합니다.";
                case XtraRichEditStringId.MenuCmd_ClearUndo: return " ClearUndo";
                case XtraRichEditStringId.MenuCmd_ClearUndoDescription: return " 취소 버퍼 지우기";
                case XtraRichEditStringId.MenuCmd_ClosePageHeaderFooter: return " 닫기 머리글 및 바닥글";
                case XtraRichEditStringId.MenuCmd_ClosePageHeaderFooterDescription: return " 닫기 머리글 및 바닥글 도구입니다. 더블 클릭 합니다.편집으로 돌아가려면 문서 영역";
                case XtraRichEditStringId.MenuCmd_CollapseOrExpandFormulaBar: return " 수식 입력줄 확장 또는 축소";
                case XtraRichEditStringId.MenuCmd_Comment: return " 보기 댓글";
                case XtraRichEditStringId.MenuCmd_CommentDescription: return " 문서에 코멘트를 강조 하 여 여부를 선택 합니다.";
                case XtraRichEditStringId.MenuCmd_CopySelection: return " 복사";
                case XtraRichEditStringId.MenuCmd_CopySelectionDescription: return " 선택한 텍스트를 복사하여 클립 보드에 넣습니다.";
                case XtraRichEditStringId.MenuCmd_CreateBookmark: return " 책갈피 만들기";
                case XtraRichEditStringId.MenuCmd_CreateBookmarkDescription: return " 책갈피 만들기";
                case XtraRichEditStringId.MenuCmd_CreateField: return " 필드 만들기";
                case XtraRichEditStringId.MenuCmd_CreateFieldDescription: return " 필드 만들기";
                case XtraRichEditStringId.MenuCmd_CreateHyperlink: return " CreateHyperlink";
                case XtraRichEditStringId.MenuCmd_CreateHyperlinkDescription: return " CreateHyperlinkDescription";
                case XtraRichEditStringId.MenuCmd_CutSelection: return " 잘라 내기";
                case XtraRichEditStringId.MenuCmd_CutSelectionDescription: return " 선택한 텍스트를 잘라내어 클립 보드에 넣습니다.";
                case XtraRichEditStringId.MenuCmd_DecreaseFontSize: return " 글꼴 축소";
                case XtraRichEditStringId.MenuCmd_DecreaseFontSizeDescription: return " 글꼴 크기를 축소합니다.";
                case XtraRichEditStringId.MenuCmd_DecrementFontSize: return " DecrementFontSize";
                case XtraRichEditStringId.MenuCmd_DecrementFontSizeDescription: return " DecrementFontSize";
                case XtraRichEditStringId.MenuCmd_DecrementIndent: return " 내어쓰기";
                case XtraRichEditStringId.MenuCmd_DecrementNumerationFromParagraph: return " DecrementNumerationFromParagraph";
                case XtraRichEditStringId.MenuCmd_DecrementNumerationFromParagraphDescription: return " DecrementNumerationFromParagraph";
                case XtraRichEditStringId.MenuCmd_DecrementParagraphLeftIndent: return " DecrementParagraphLeftIndent";
                case XtraRichEditStringId.MenuCmd_DecrementParagraphLeftIndentDescription: return " DecrementParagraphLeftIndentDescription";
                case XtraRichEditStringId.MenuCmd_Delete: return " 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteAllComments: return " 모든 코멘트를 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteAllCommentsDescription: return " 모든 코멘트를 삭제 합니다.";
                case XtraRichEditStringId.MenuCmd_DeleteAllCommentsShown: return " 삭제 표시 된 모든 의견";
                case XtraRichEditStringId.MenuCmd_DeleteAllCommentsShownDescription: return " 표시 된 모든 코멘트를 삭제 합니다.";
                case XtraRichEditStringId.MenuCmd_DeleteBack: return " DeleteBack";
                case XtraRichEditStringId.MenuCmd_DeleteBackCore: return " DeleteBackCore";
                case XtraRichEditStringId.MenuCmd_DeleteBackCoreDescription: return " DeleteBackCoreDescription";
                case XtraRichEditStringId.MenuCmd_DeleteBackDescription: return " DeleteBack";
                case XtraRichEditStringId.MenuCmd_DeleteBookmark: return " 책갈피 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteBookmarkDescription: return " 책갈피 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteComment: return " 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteDescription: return " 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteRepeatedWord: return " 중복 단어 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteRepeatedWordDescription: return " 중복 단어 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTable: return " 테이블 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableCells: return " 셀 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableCellsDescription: return " 행, 열 또는 셀 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableCellsMenuItem: return " 삭제 셀...";
                case XtraRichEditStringId.MenuCmd_DeleteTableColumns: return " 열 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableColumnsDescription: return " 열 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableElements: return " 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableElementsDescription: return " 셀, 행, 열 또는 테이블 전체를 삭제합니다.";
                case XtraRichEditStringId.MenuCmd_DeleteTableRows: return " 행 삭제";
                case XtraRichEditStringId.MenuCmd_DeleteTableRowsDescription: return " 행 삭제";
                case XtraRichEditStringId.MenuCmd_DeselectAll: return " 모든 선택 해제";
                case XtraRichEditStringId.MenuCmd_DeselectAllDescription: return " 문서의 선택 영역을 재설정합니다.";
                case XtraRichEditStringId.MenuCmd_DraftView: return " 초안 보기";
                case XtraRichEditStringId.MenuCmd_DraftViewDescription: return " 초안 보기";
                case XtraRichEditStringId.MenuCmd_EditPageFooter: return " 바닥글";
                case XtraRichEditStringId.MenuCmd_EditPageFooterDescription: return " 편집 문서의 바닥글입니다. 바닥글에서 콘텐츠 인쇄 된 각 페이지의 하단에 표시 됩니다.";
                case XtraRichEditStringId.MenuCmd_EditPageHeader: return " 헤더";
                case XtraRichEditStringId.MenuCmd_EditPageHeaderDescription: return " 편집 문서의 헤더입니다.콘텐츠 헤더에 인쇄 된 각 페이지의 상단에 표시 됩니다.";
                case XtraRichEditStringId.MenuCmd_Find: return " 검색";
                case XtraRichEditStringId.MenuCmd_FindDescription: return " 문서에서 텍스트를 검색합니다.";
                case XtraRichEditStringId.MenuCmd_FindNext: return " 다음 찾기";
                case XtraRichEditStringId.MenuCmd_FindPrev: return " 이전 찾기";
                case XtraRichEditStringId.MenuCmd_FirstDataRecord: return " 첫 번째 레코드";
                case XtraRichEditStringId.MenuCmd_FirstDataRecordDescription: return " 첫 번째 레코드";
                case XtraRichEditStringId.MenuCmd_FloatingObjectBringForward: return " 앞으로 이동";
                case XtraRichEditStringId.MenuCmd_FloatingObjectBringForwardDescription: return " 선택한 개체를 앞으로 이동합니다.";
                case XtraRichEditStringId.MenuCmd_FloatingObjectBringForwardPlaceholder: return " 앞으로 이동";
                case XtraRichEditStringId.MenuCmd_FloatingObjectBringForwardPlaceholderDescription: return " 선택한 개체를 앞으로 이동합니다.";
                case XtraRichEditStringId.MenuCmd_FloatingObjectBringInFrontOfText: return " 텍스트의 맨 앞으로 이동";
                case XtraRichEditStringId.MenuCmd_FloatingObjectBringToFront: return " 맨 앞으로 가져오기";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendBackward: return " 뒤로 보내기";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendBackwardDescription: return " 개체는 그것 앞으로 숨겨져 있도록 이전 버전과 선택한 개체 보내기";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendBackwardPlaceholder: return " 뒤로 보내기";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendBackwardPlaceholderDescription: return " 개체는 그것 앞으로 숨겨져 있도록 이전 버전과 선택한 개체 보내기";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendBehindText: return " 텍스트 뒤로 이동";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendToBack: return " 뒤로 보내기";
                case XtraRichEditStringId.MenuCmd_FloatingObjectSendToBackDescription: return " 선택된 개체를 모든 개체의 뒤로 이동합니다.";
                case XtraRichEditStringId.MenuCmd_FontSubscript: return " 아래 첨자";
                case XtraRichEditStringId.MenuCmd_FontSubscriptDescription: return " 작은 문자를 텍스트 행 아래에 만듭니다.";
                case XtraRichEditStringId.MenuCmd_FontSuperscript: return " 위 첨자";
                case XtraRichEditStringId.MenuCmd_FontSuperscriptDescription: return " 텍스트 줄 위에 작은 글자를 만듭니다.";
                case XtraRichEditStringId.MenuCmd_GoToNextHeaderFooterDescription: return " 다음 섹션의 머리글 또는 바닥글 이동 합니다.";
                case XtraRichEditStringId.MenuCmd_GoToPage: return " 페이지로 이동";
                case XtraRichEditStringId.MenuCmd_GoToPageDescription: return " 페이지로 이동";
                case XtraRichEditStringId.MenuCmd_GoToPageFooter: return " 바닥글로 이동";
                case XtraRichEditStringId.MenuCmd_GoToPageHeader: return " 머리글로 이동";
                case XtraRichEditStringId.MenuCmd_GoToPreviousHeaderFooter: return " 이전 보기";
                case XtraRichEditStringId.MenuCmd_GoToPreviousHeaderFooterDescription: return " 이전 섹션의 머리글과 바닥글로 이동합니다.";
                case XtraRichEditStringId.MenuCmd_HighlightText: return " 형광펜";
                case XtraRichEditStringId.MenuCmd_HighlightTextDescription: return " 형광펜으로 표시 한 바와 같이, 텍스트의 배경색을 변경합니다.";
                case XtraRichEditStringId.MenuCmd_Hyperlink: return " 하이퍼링크...";
                case XtraRichEditStringId.MenuCmd_HyperlinkDescription: return " 하이퍼링크...";
                case XtraRichEditStringId.MenuCmd_IgnoreAllMistakenWords: return " 모두 무시";
                case XtraRichEditStringId.MenuCmd_IgnoreAllMistakenWordsDescription: return " 모두 무시";
                case XtraRichEditStringId.MenuCmd_IgnoreMistakenWord: return " 무시";
                case XtraRichEditStringId.MenuCmd_IgnoreMistakenWordDescription: return " 무시";
                case XtraRichEditStringId.MenuCmd_IncreaseFontSizeDescription: return " 글꼴 크기를 증가 합니다.";
                case XtraRichEditStringId.MenuCmd_IncrementIndent: return " 들여쓰기";
                case XtraRichEditStringId.MenuCmd_IncrementIndentDescription: return " 단락의 들여쓰기 수준을 높입니다.";
                case XtraRichEditStringId.MenuCmd_InsertBreak: return " 구분";
                case XtraRichEditStringId.MenuCmd_InsertBreakDescription: return " 문서에 페이지, 섹션 또는 열 구분을 추가합니다.";
                case XtraRichEditStringId.MenuCmd_InsertBulletList: return " 글머리 기호";
                case XtraRichEditStringId.MenuCmd_InsertBulletListDescription: return " 글머리 기호 목록을 시작 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertCaptionPlaceholder: return " 캡션 삽입";
                case XtraRichEditStringId.MenuCmd_InsertCaptionPlaceholderDescription: return " 는 그림 이나 다른 이미지에 캡션 추가 합니다. 캡션에 그것을 설명 하는 개체 아래에 표시 되는 텍스트 줄";
                case XtraRichEditStringId.MenuCmd_InsertClosingDoubleQuotationMark: return " InsertClosingDoubleQuotationMark";
                case XtraRichEditStringId.MenuCmd_InsertClosingDoubleQuotationMarkDescription: return " InsertClosingDoubleQuotationMark";
                case XtraRichEditStringId.MenuCmd_InsertColumnBreak: return " 열";
                case XtraRichEditStringId.MenuCmd_InsertColumnBreakDescription: return " 표시 한 단 나누기 다음에 오는 텍스트는 다음 열에서 시작 됩니다.";
                case XtraRichEditStringId.MenuCmd_InsertCopyrightSymbol: return " InsertCopyrightSymbol";
                case XtraRichEditStringId.MenuCmd_InsertCopyrightSymbolDescription: return " InsertCopyrightSymbol";
                case XtraRichEditStringId.MenuCmd_InsertEquationsCaption: return " 방정식 캡션";
                case XtraRichEditStringId.MenuCmd_InsertEquationsCaptionDescription: return " 방정식 캡션을 추가 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertField: return " InsertField";
                case XtraRichEditStringId.MenuCmd_InsertFieldDescription: return " InsertField";
                case XtraRichEditStringId.MenuCmd_InsertFiguresCaption: return " 그림 캡션";
                case XtraRichEditStringId.MenuCmd_InsertFiguresCaptionDescription: return " 그림 캡션을 추가 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertFloatingObjectPicture: return " 이미지";
                case XtraRichEditStringId.MenuCmd_InsertHyperlink: return " InsertHyperlink";
                case XtraRichEditStringId.MenuCmd_InsertMergeField: return " 병합 필드 삽입";
                case XtraRichEditStringId.MenuCmd_InsertMergeFieldDescription: return " 병합 필드 삽입";
                case XtraRichEditStringId.MenuCmd_InsertMultilevelList: return " 개요";
                case XtraRichEditStringId.MenuCmd_InsertMultilevelListDescription: return " 개요 목록을 시작합니다.";
                case XtraRichEditStringId.MenuCmd_InsertOpeningDoubleQuotationMark: return " InsertOpeningDoubleQuotationMark";
                case XtraRichEditStringId.MenuCmd_InsertOpeningDoubleQuotationMarkDescription: return " InsertOpeningDoubleQuotationMark";
                case XtraRichEditStringId.MenuCmd_InsertPageBreak: return " 페이지 나누기";
                case XtraRichEditStringId.MenuCmd_InsertPageBreak2: return " 페이지 나누기";
                case XtraRichEditStringId.MenuCmd_InsertPageBreak2Description: return " 현재 위치에서 다음 페이지를 시작 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertPageBreakDescription: return " 현재 위치에서 다음 페이지를 시작합니다.";
                case XtraRichEditStringId.MenuCmd_InsertPageCountField: return " 페이지 수";
                case XtraRichEditStringId.MenuCmd_InsertPageCountFieldDescription: return " 문서에 총 페이지 수를 삽입합니다.";
                case XtraRichEditStringId.MenuCmd_InsertPageNumberField: return " 페이지 번호";
                case XtraRichEditStringId.MenuCmd_InsertPageNumberFieldDescription: return " 문서에 페이지 번호를 삽입합니다.";
                case XtraRichEditStringId.MenuCmd_InsertPicture: return " 인라인 이미지";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakContinuous: return " 섹션 (연속)";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakContinuousDescription: return " 구역 나누기를 삽입하여 동일한 페이지에 섹션을 시작합니다.";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakEvenPage: return " 섹션 (짝수 페이지)";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakEvenPageDescription: return " 구역 나누기를 삽입 하 고 다음 짝수 페이지에서 새 구역을 시작 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakNextPage: return " 섹션 (다음 페이지)";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakNextPageDescription: return " 구역 나누기를 삽입 하 고 다음 페이지에서 새 구역을 시작 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakOddPage: return " 섹션 (홀수 페이지)";
                case XtraRichEditStringId.MenuCmd_InsertSectionBreakOddPageDescription: return " 구역 나누기를 삽입하고 다음 홀수 페이지에 섹션을 시작합니다.";
                case XtraRichEditStringId.MenuCmd_InsertSimpleList: return " 번호 매기기";
                case XtraRichEditStringId.MenuCmd_InsertSimpleListDescription: return " 번호 매기기 목록을 시작 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertSymbol: return " 기호";
                case XtraRichEditStringId.MenuCmd_InsertSymbolDescription: return " 는 저작권 기호, 상표 기호, 등 키보드에 없는 단락 표시 및 유니코드 문자 기호를 삽입 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertTable: return " 테이블";
                case XtraRichEditStringId.MenuCmd_InsertTableCells: return " 셀 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTableCellsDescription: return " 셀 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTableColumnToTheLeft: return " 열을 왼쪽에 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTableColumnToTheLeftDescription: return " 선택한 열의 왼쪽에 새 열을 추가합니다.";
                case XtraRichEditStringId.MenuCmd_InsertTableColumnToTheRight: return " 열을 오른쪽에 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTableColumnToTheRightDescription: return " 선택한 열의 오른쪽에 새 열을 추가합니다.";
                case XtraRichEditStringId.MenuCmd_InsertTableDescription: return " 문서에 표를 삽입 합니다.";
                case XtraRichEditStringId.MenuCmd_InsertTableElement: return " 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTableOfContents: return " 목차";
                case XtraRichEditStringId.MenuCmd_InsertTableOfEquations: return " 방정식 테이블";
                case XtraRichEditStringId.MenuCmd_InsertTableOfFigures: return " 그림 테이블";
                case XtraRichEditStringId.MenuCmd_InsertTableOfTables: return " 테이블 목록";
                case XtraRichEditStringId.MenuCmd_InsertTableRowAbove: return " 행을 위에 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTableRowAboveDescription: return " 행 바로 위에 새 행을 추가합니다.";
                case XtraRichEditStringId.MenuCmd_InsertTableRowBelow: return " 아래에 행 삽입";
                case XtraRichEditStringId.MenuCmd_InsertTablesCaption: return " 테이블 캡션";
                case XtraRichEditStringId.MenuCmd_InsertTextBox: return " 텍스트 상자";
                case XtraRichEditStringId.MenuCmd_InsertTextBoxDescription: return " 문서에 텍스트 상자를 삽입합니다.";
                case XtraRichEditStringId.MenuCmd_InsertTrademarkSymbol: return " InsertTrademarkSymbol";
                case XtraRichEditStringId.MenuCmd_InsertTrademarkSymbolDescription: return " InsertTrademarkSymbol";
                case XtraRichEditStringId.MenuCmd_LastDataRecord: return " 마지막 레코드";
                case XtraRichEditStringId.MenuCmd_LastDataRecordDescription: return " 마지막 레코드";
                case XtraRichEditStringId.MenuCmd_LoadDocument: return " 열기";
                case XtraRichEditStringId.MenuCmd_LoadDocumentDescription: return " 문서를 엽니다.";
                case XtraRichEditStringId.MenuCmd_MailMergeSaveDocumentAsCommand: return " 편지 병합";
                case XtraRichEditStringId.MenuCmd_MailMergeSaveDocumentAsCommandDescription: return " 편지 병합";
                case XtraRichEditStringId.MenuCmd_MakeTextLowerCase: return " 소문자";
                case XtraRichEditStringId.MenuCmd_MakeTextLowerCaseDescription: return " 선택한 텍스트를 소문자로 변환합니다.";
                case XtraRichEditStringId.MenuCmd_MakeTextUpperCase: return " 대문자";
                case XtraRichEditStringId.MenuCmd_MakeTextUpperCaseDescription: return " 선택한 텍스트를 대문자로 변환합니다.";
                case XtraRichEditStringId.MenuCmd_MergeTableCells: return " 셀 병합";
                case XtraRichEditStringId.MenuCmd_MergeTableCellsDescription: return " 선택한 셀을 하나의 셀로 병합합니다.";
                case XtraRichEditStringId.MenuCmd_MoveNextPage: return " MoveNextPage";
                case XtraRichEditStringId.MenuCmd_MoveNextPageDescription: return " MoveNextPage";
                case XtraRichEditStringId.MenuCmd_MovePreviousPage: return " MovePreviousPage";
                case XtraRichEditStringId.MenuCmd_MovePreviousPageDescription: return " MovePreviousPage";
                case XtraRichEditStringId.MenuCmd_MoveToStartOfLine: return " MoveToBeginOfLine";
                case XtraRichEditStringId.MenuCmd_MoveToStartOfLineDescription: return " MoveToBeginOfLine";
                case XtraRichEditStringId.MenuCmd_NewCommentDescription: return " 는 선택에 대 한 코멘트를 추가 합니다.";
                case XtraRichEditStringId.MenuCmd_NewEmptyDocument: return " 새로 만들기";
                case XtraRichEditStringId.MenuCmd_NewEmptyDocumentDescription: return " 새 문서를 만듭니다.";
                case XtraRichEditStringId.MenuCmd_NextComment: return " 다음";
                case XtraRichEditStringId.MenuCmd_NextCommentDescription: return " 문서에서 다음 의견을 이동 합니다.";
                case XtraRichEditStringId.MenuCmd_NextDataRecord: return " 다음 레코드";
                case XtraRichEditStringId.MenuCmd_NextDataRecordDescription: return " 다음 레코드";
                case XtraRichEditStringId.MenuCmd_NextRevision: return " 다음";
                case XtraRichEditStringId.MenuCmd_OpenHyperlink: return " 하이퍼링크 열기";
                case XtraRichEditStringId.MenuCmd_OpenHyperlinkDescription: return " 하이퍼링크 열기";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentCenter: return " 중앙";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentCenterDescription: return " 텍스트를 가운데에 맞춥니다.";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentJustify: return " 양쪽 맞춤";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentJustifyDescription: return " 정렬 텍스트 왼쪽 및 오른쪽 여백에 필요에 따라 단어 사이 여분의 공간을 추가 합니다. 이 왼쪽 및 오른쪽 페이지에 따라 깨끗 한 모습을 만듭니다.";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentLeft: return " 텍스트 왼쪽 정렬";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentLeftDescription: return " 텍스트를 왼쪽 정렬 합니다.";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentRight: return " 텍스트 오른쪽 정렬";
                case XtraRichEditStringId.MenuCmd_Paste: return " 붙여넣기";
                case XtraRichEditStringId.MenuCmd_PasteDescription: return " 클립 보드의 내용을 붙여 넣습니다.";
                case XtraRichEditStringId.MenuCmd_PasteFiles: return " 파일";
                case XtraRichEditStringId.MenuCmd_PasteFilesDescription: return " 클립 보드의 내용을 포함 파일로 삽입합니다.";
                case XtraRichEditStringId.MenuCmd_PasteHtmlText: return " HTML 형식";
                case XtraRichEditStringId.MenuCmd_PasteHtmlTextDescription: return " 클립 보드의 내용을 HTML로 삽입합니다.";
                case XtraRichEditStringId.MenuCmd_PasteImage: return " 이미지";
                case XtraRichEditStringId.MenuCmd_PasteMetafileImage: return " 메타 파일";
                case XtraRichEditStringId.MenuCmd_PastePlainText: return " 서식 없는 텍스트";
                case XtraRichEditStringId.MenuCmd_PasteRtfText: return " 서식 텍스트 (RTF)";
                case XtraRichEditStringId.MenuCmd_PasteSilverlightXamlText: return " 서식 텍스트 (XAML)";
                case XtraRichEditStringId.MenuCmd_PreviousComment: return " 이전";
                case XtraRichEditStringId.MenuCmd_PreviousDataRecord: return " 이전 레코드";
                case XtraRichEditStringId.MenuCmd_PreviousDataRecordDescription: return " 이전 레코드";
                case XtraRichEditStringId.MenuCmd_PrevRevision: return " 이전";
                case XtraRichEditStringId.MenuCmd_Print: return " 인쇄 (&P)";
                case XtraRichEditStringId.MenuCmd_PrintDescription: return " 프린터, 매수 및 인쇄 하기 전에 다른 인쇄 옵션을 선택 합니다.";
                case XtraRichEditStringId.MenuCmd_PrintPreview: return " 인쇄 미리보기 (&V)";
                case XtraRichEditStringId.MenuCmd_PrintPreviewDescription: return " 인쇄 하기 전에 페이지를 미리 봅니다.";
                case XtraRichEditStringId.MenuCmd_PrintView: return " 인쇄보기";
                case XtraRichEditStringId.MenuCmd_PrintViewDescription: return " 인쇄보기";
                case XtraRichEditStringId.MenuCmd_ProtectDocument: return " 문서 보호";
                case XtraRichEditStringId.MenuCmd_ProtectDocumentDescription: return " 암호를 지정하여 문서 편집을 제한합니다.";
                case XtraRichEditStringId.MenuCmd_QuickPrint: return " 빠른 인쇄 (&Q)";
                case XtraRichEditStringId.MenuCmd_QuickPrintDescription: return " 직접 기본 프린터 변경 하지 않고 문서를 보냅니다.";
                case XtraRichEditStringId.MenuCmd_ReadingView: return " 읽기용 보기";
                case XtraRichEditStringId.MenuCmd_ReadingViewDescription: return " 읽기용 보기";
                case XtraRichEditStringId.MenuCmd_Redo: return " 다시 실행";
                case XtraRichEditStringId.MenuCmd_RedoDescription: return " 다시 실행";
                case XtraRichEditStringId.MenuCmd_RemoveHyperlink: return " 하이퍼링크 제거";
                case XtraRichEditStringId.MenuCmd_RemoveHyperlinkDescription: return " 하이퍼링크 제거";
                case XtraRichEditStringId.MenuCmd_Replace: return " 바꾸기";
                case XtraRichEditStringId.MenuCmd_ReplaceDescription: return " 문서에서 텍스트를 바꿉니다.";
                case XtraRichEditStringId.MenuCmd_ResetCharacterFormatting: return " 문자 서식 재설정";
                case XtraRichEditStringId.MenuCmd_ResetTableCellsBorders: return " 테두리 없음";
                case XtraRichEditStringId.MenuCmd_ResetTableCellsBordersDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_SaveDocument: return " 저장";
                case XtraRichEditStringId.MenuCmd_SaveDocumentAs: return " 다른 이름으로 저장";
                case XtraRichEditStringId.MenuCmd_SaveDocumentAsDescription: return " 다른 이름으로 저장합니다.";
                case XtraRichEditStringId.MenuCmd_ScrollDown: return " 아래로 스크롤";
                case XtraRichEditStringId.MenuCmd_ScrollDownDescription: return " 아래로 스크롤";
                case XtraRichEditStringId.MenuCmd_ScrollToPage: return " ScrollToPage";
                case XtraRichEditStringId.MenuCmd_ScrollToPageDescription: return " ScrollToPage";
                case XtraRichEditStringId.MenuCmd_SelectAll: return " 모두 선택";
                case XtraRichEditStringId.MenuCmd_SelectAllDescription: return " 전체 문서 내용을 선택합니다.";
                case XtraRichEditStringId.MenuCmd_SelectBookmark: return " 책갈피 선택";
                case XtraRichEditStringId.MenuCmd_SelectBookmarkDescription: return " 책갈피 선택";
                case XtraRichEditStringId.MenuCmd_SelectTable: return " 테이블 선택";
                case XtraRichEditStringId.MenuCmd_SelectTableDescription: return " 테이블 선택";
                case XtraRichEditStringId.MenuCmd_SelectTableElements: return " 선택";
                case XtraRichEditStringId.MenuCmd_SelectTableElementsDescription: return " 현재 셀, 행, 열 또는 전체 테이블을 선택합니다.";
                case XtraRichEditStringId.MenuCmd_SelectTableRow: return " 테이블 행 선택";
                case XtraRichEditStringId.MenuCmd_SelectTableRowDescription: return " 테이블 행 선택";
                case XtraRichEditStringId.MenuCmd_SetDoubleParagraphSpacing: return " 2";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectBehindTextWrapType: return " 텍스트 뒤에";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectBottomCenterAlignmentDescription: return " 중앙 하단에 배치하고 사각의 틀에 따라 텍스트 줄 바꿈";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectBottomRightAlignmentDescription: return " 오른쪽 하단에 배치하여 사각의 틀에 따라 텍스트 줄 바꿈";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectSquareTextWrapType: return " 사각";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectThroughTextWrapType: return " 내부";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectTopAndBottomTextWrapType: return " 상하";
                case XtraRichEditStringId.MenuCmd_SetFloatingObjectTopLeftAlignmentDescription: return " 왼쪽 상단에 배치하고 사각의 틀에 따라 텍스트 줄 바꿈";
                case XtraRichEditStringId.MenuCmd_SetHyphenateDocumentAutomatic: return " 자동";
                case XtraRichEditStringId.MenuCmd_SetHyphenateDocumentNone: return " 없음";
                case XtraRichEditStringId.MenuCmd_SetParagraphBodyTextLevel: return " 목차에 표시 하지 않습니다";
                case XtraRichEditStringId.MenuCmd_SetParagraphBodyTextLevelDescription: return " 목차에 표시 하지 않습니다";
                case XtraRichEditStringId.MenuCmd_SetParagraphHeadingLevel: return " 레벨 {0}";
                case XtraRichEditStringId.MenuCmd_SetParagraphHeadingLevelDescription: return " 레벨 {0}";
                case XtraRichEditStringId.MenuCmd_SetPortraitPageOrientation: return " 세로";
                case XtraRichEditStringId.MenuCmd_SetSectionColumns: return " 열";
                case XtraRichEditStringId.MenuCmd_SetSectionColumnsDescription: return " 텍스트를 두 개 이상의 열에 나눕니다.";
                case XtraRichEditStringId.MenuCmd_SetSectionLineNumberingContinuous: return " 계속";
                case XtraRichEditStringId.MenuCmd_SetSectionLineNumberingContinuousDescription: return " 계속";
                case XtraRichEditStringId.MenuCmd_SetSectionLineNumberingNone: return " 없음";
                case XtraRichEditStringId.MenuCmd_SetSectionLineNumberingNoneDescription: return " 행 번호 없음";
                case XtraRichEditStringId.MenuCmd_SetSectionLineNumberingRestartNewPage: return " 각 페이지를 다시 시작";
                case XtraRichEditStringId.MenuCmd_SetSectionLineNumberingRestartNewPageDescription: return " 각 페이지를 다시 시작";
                case XtraRichEditStringId.MenuCmd_SetSectionOneColumn: return " 하나";
                case XtraRichEditStringId.MenuCmd_SetSectionThreeColumns: return " 3 개";
                case XtraRichEditStringId.MenuCmd_SetSectionTwoColumns: return " 2 개";
                case XtraRichEditStringId.MenuCmd_SetSesquialteralParagraphSpacing: return " 1.5";
case XtraRichEditStringId.MenuCmd_ShiftTabKey: return " ShiftTabKey";
                case XtraRichEditStringId.MenuCmd_ShiftTabKeyDescription: return " ShiftTabKey";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldCodes: return " 모든 필드 코드 표시";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldCodesDescription: return " 모든 필드 코드 표시";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldResults: return " 모든 필드 결과 표시";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldResultsDescription: return " 모든 필드 결과 표시";
                case XtraRichEditStringId.MenuCmd_ShowBookmarkForm: return " 책갈피";
                case XtraRichEditStringId.MenuCmd_ShowBookmarkFormDescription: return " 문서에서 특정 지점에는 이름을 할당 하는 책갈피 만들기 책갈피 위치로 직접 이동 하는 하이퍼링크를 만들 수 있습니다.";
                case XtraRichEditStringId.MenuCmd_ShowColumnsSetupForm: return " 추가 열 표시";
                case XtraRichEditStringId.MenuCmd_ShowColumnsSetupFormDescription: return " 열 대화 상자를 표시하여 열 너비를 지정";
                case XtraRichEditStringId.MenuCmd_ShowCommentForm: return " 코멘트";
                case XtraRichEditStringId.MenuCmd_ShowEditStyleForm: return " 편집 스타일";
                case XtraRichEditStringId.MenuCmd_ShowEditStyleFormDescription: return " 편집 스타일 대화 상자를 표시";
                case XtraRichEditStringId.MenuCmd_ShowFloatingObjectLayoutOptionsForm: return " 레이아웃";
                case XtraRichEditStringId.MenuCmd_ShowFloatingObjectLayoutOptionsFormDescription: return " 레이아웃 대화 상자를 표시 합니다.";
                case XtraRichEditStringId.MenuCmd_ShowFontForm: return " 글꼴...";
                case XtraRichEditStringId.MenuCmd_ShowFontFormDescription: return " 글꼴 대화 상자를 표시 합니다.";
                case XtraRichEditStringId.MenuCmd_ShowHyperlinkForm: return " 하이퍼링크 ";
                case XtraRichEditStringId.MenuCmd_ShowHyperlinkFormDescription: return " Web 페이지, 이미지, 전자 메일 주소, 프로그램 등에 대한 링크를 만듭니다.";
                case XtraRichEditStringId.MenuCmd_ShowInsertMergeFieldForm: return " 병합 필드 삽입";
                case XtraRichEditStringId.MenuCmd_ShowLineNumberingForm: return " 줄 번호 옵션";
                case XtraRichEditStringId.MenuCmd_ShowLineNumberingFormDescription: return " 줄 번호 옵션";
                case XtraRichEditStringId.MenuCmd_ShowLineSpacingForm: return " 줄 간격 옵션...";
                case XtraRichEditStringId.MenuCmd_ShowNumberingListDescription: return " 번호 매기기 목록 대화 상자를 표시합니다.";
                case XtraRichEditStringId.MenuCmd_ShowPageMarginsSetupForm: return " 사용자 지정 여백";
                case XtraRichEditStringId.MenuCmd_ShowPagePaperSetupForm: return " 다른 용지 크기";
                case XtraRichEditStringId.MenuCmd_ShowPageSetupForm: return " 페이지 설정";
                case XtraRichEditStringId.MenuCmd_ShowPageSetupFormDescription: return " 페이지 설정 대화 상자를 표시";
                case XtraRichEditStringId.MenuCmd_ShowParagraphForm: return " 단락...";
                case XtraRichEditStringId.MenuCmd_ShowParagraphFormDescription: return " 단락 대화 상자를 표시합니다.";
                case XtraRichEditStringId.MenuCmd_ShowPasteSpecialFormDescription: return " 형식을 선택하고 붙여 넣습니다.";
                case XtraRichEditStringId.MenuCmd_ShowRangeEditingPermissionsForm: return " 범위 편집 허용";
                case XtraRichEditStringId.MenuCmd_ShowRangeEditingPermissionsFormDescription: return " 범위 편집 허용";
                case XtraRichEditStringId.MenuCmd_ShowSymbol: return " 기호";
                case XtraRichEditStringId.MenuCmd_ShowSymbolDescription: return " 기호 대화 상자를 표시합니다.";
                case XtraRichEditStringId.MenuCmd_ShowTableOptionsForm: return " 셀 여백";
                case XtraRichEditStringId.MenuCmd_ShowTableOptionsFormDescription: return " 셀의 여백과 간격을 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ShowTablePropertiesForm: return " 속성";
                case XtraRichEditStringId.MenuCmd_ShowTablePropertiesFormDescriptionMenuItem: return " 테이블 속성 대화 상자를 표시합니다.";
                case XtraRichEditStringId.MenuCmd_ShowTabsForm: return " 탭...";
                case XtraRichEditStringId.MenuCmd_ShowTabsFormDescription: return " 탭";
                case XtraRichEditStringId.MenuCmd_ShowWatermarkForm: return " 워터 마크";
                case XtraRichEditStringId.MenuCmd_SimpleView: return " 심플 뷰";
                case XtraRichEditStringId.MenuCmd_SimpleViewDescription: return " 심플 뷰";
                case XtraRichEditStringId.MenuCmd_SplitTableCells: return " 셀 분할";
                case XtraRichEditStringId.MenuCmd_SplitTableCellsDescription: return " 테이블 셀을 분리";
                case XtraRichEditStringId.MenuCmd_SplitTableCellsMenuItem: return " 셀 분할...";
                case XtraRichEditStringId.MenuCmd_SwitchToDraftView: return " 초안 보기";
                case XtraRichEditStringId.MenuCmd_SwitchToPrintLayoutView: return " 인쇄 레이아웃";
                case XtraRichEditStringId.MenuCmd_SwitchToPrintLayoutViewDescription: return " 인쇄 페이지 레이아웃 문서를 표시합니다.";
                case XtraRichEditStringId.MenuCmd_SwitchToSimpleView: return " 심플 뷰";
                case XtraRichEditStringId.MenuCmd_SwitchToSimpleViewDescription: return " 뷰는 간단한 문서 메모입니다. 이 보기는 텍스트 편집에 관심을 끌기 위해 페이지 레이아웃을 무시 합니다.";
                case XtraRichEditStringId.MenuCmd_SymbolFormInsertButton: return " 삽입";
                case XtraRichEditStringId.MenuCmd_ToggleDifferentFirstPage: return " 첫 페이지를 다르게 설정";
                case XtraRichEditStringId.MenuCmd_ToggleDifferentOddAndEvenPages: return " 홀수와 짝수 페이지의 다른 설정";
                case XtraRichEditStringId.MenuCmd_ToggleFieldCodes: return " 필드 코드 전환";
                case XtraRichEditStringId.MenuCmd_ToggleFieldCodesDescription: return " 필드 코드 전환";
                case XtraRichEditStringId.MenuCmd_ToggleFontBold: return " 굵게";
                case XtraRichEditStringId.MenuCmd_ToggleFontBoldDescription: return " 선택한 텍스트를 굵게 합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleStrikeout: return " 이중 취소선";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleStrikeoutDescription: return " 이중 취소선";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleUnderline: return " 이중 밑줄";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleUnderlineDescription: return " 이중 밑줄";
                case XtraRichEditStringId.MenuCmd_ToggleFontItalic: return " 기울임꼴";
                case XtraRichEditStringId.MenuCmd_ToggleFontStrikeout: return " 취소선";
                case XtraRichEditStringId.MenuCmd_ToggleFontUnderline: return " 밑줄";
                case XtraRichEditStringId.MenuCmd_ToggleFontUnderlineDescription: return " 선택한 텍스트에 밑줄을 긋습니다.";
                case XtraRichEditStringId.MenuCmd_ToggleHeaderFooterLinkToPrevious: return " 이전 링크";
                case XtraRichEditStringId.MenuCmd_ToggleHeaderFooterLinkToPreviousDescription: return " 이전 단원에서와 마찬가지로 동일한 콘텐츠를 포함 하는 머리글과 바닥글을 현재 구역에 이전 섹션을 연결 합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleHiddenText: return " 숨기기";
                case XtraRichEditStringId.MenuCmd_ToggleHiddenTextDescription: return " 숨깁니다.";
                case XtraRichEditStringId.MenuCmd_ToggleShowHorizontalRuler: return " 가로 눈금자";
                case XtraRichEditStringId.MenuCmd_ToggleShowHorizontalRulerDescription: return " 측정 하 고 문서에서 개체를 줄 사용 가로 눈금자를 보려면.";
                case XtraRichEditStringId.MenuCmd_ToggleShowTableGridLines: return " 눈금선 보기";
                case XtraRichEditStringId.MenuCmd_ToggleShowVerticalRuler: return " 세로 눈금자";
                case XtraRichEditStringId.MenuCmd_ToggleShowVerticalRulerDescription: return " 측정 하 고 문서에서 개체를 줄 사용 세로 눈금자를 보려면.";
                case XtraRichEditStringId.MenuCmd_ToggleSpellCheckAsYouType: return " 자동 맞춤법 ​​검사";
                case XtraRichEditStringId.MenuCmd_ToggleSpellCheckAsYouTypeDescription: return " 자동 맞춤법 ​​검사";
                case XtraRichEditStringId.MenuCmd_ToggleTableAutoFitPlaceholder: return " 자동 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableAutoFitWindow: return " 창을 자동 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsAllBorders: return " 모든 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsAllBordersDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomBorder: return " 아래쪽 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomRightAlignmentDescription: return " 텍스트를 셀의 아래에 배치하고 오른쪽에 맞춥니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsInsideBorder: return " 안쪽 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsInsideBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsInsideHorizontalBorder: return " 안쪽 가로 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsInsideHorizontalBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsInsideVerticalBorder: return " 안쪽 세로 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsInsideVerticalBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsLeftBorder: return " 왼쪽 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsLeftBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleCenterAlignmentDescription: return " 텍스트를 세로와 가로의 중앙에 맞춥니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleLeftAlignmentDescription: return " 텍스트를 수직 중앙에 배치하고 셀의 왼쪽에 맞춥니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleRightAlignmentDescription: return " 텍스트를 수직 중앙에 배치하고 셀의 오른쪽에 맞춥니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsOutsideBorder: return " 외부 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsOutsideBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsRightBorder: return " 오른쪽 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsRightBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopBorder: return " 위쪽 테두리";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopBorderDescription: return " 선택한 셀의 테두리를 사용자 지정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopRightAlignmentDescription: return " 텍스트를 셀 위에 오른쪽에 맞춥니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTableFixedColumnWidth: return " 고정 열 너비";
                case XtraRichEditStringId.MenuCmd_ToggleTableFixedColumnWidthDescription: return " 테이블의 폭을 고정 값으로 설정합니다.";
                case XtraRichEditStringId.MenuCmd_ToggleTextCase: return " 대/소문자 전환";
                case XtraRichEditStringId.MenuCmd_ToggleTextCaseDescription: return " 대문자와 소문자를 바꿉니다.";
                case XtraRichEditStringId.MenuCmd_ToggleViewMergedData: return " 병합 데이터보기";
                case XtraRichEditStringId.MenuCmd_ToggleViewMergedDataDescription: return " 외형을 확인할 수 있도록 대상 목록에서 실제 데이터를 추출하고 문서에서 병합 필드로 바꿉니다.";
                case XtraRichEditStringId.MenuCmd_ToggleWhitespace: return " 단락 기호 표시 / 숨기기 ¶";
                case XtraRichEditStringId.MenuCmd_ToggleWhitespaceDescription: return " 단락 위치 및 숨겨진 서식 기호를 표시합니다.";
                case XtraRichEditStringId.MenuCmd_Undo: return " 취소";
                case XtraRichEditStringId.MenuCmd_UnprotectDocument: return " 문서 보호 해제";
                case XtraRichEditStringId.MenuCmd_UnprotectDocumentDescription: return " 문서 보호 해제";
                case XtraRichEditStringId.MenuCmd_UpdateTableOfContents: return " 테이블 업데이트";
                case XtraRichEditStringId.MenuCmd_UpdateTableOfContentsDescription: return " 올바른 페이지 번호를 참조 하십시오 모든 항목의 목차를 업데이트 합니다.";
                case XtraRichEditStringId.MenuCmd_UpdateTableOfFigures: return " 테이블 업데이트";
                case XtraRichEditStringId.MenuCmd_Zoom: return " 확대/축소";
                case XtraRichEditStringId.MenuCmd_ZoomDescription: return " 확대/축소";
                case XtraRichEditStringId.MenuCmd_ZoomIn: return " 확대";
                case XtraRichEditStringId.MenuCmd_ZoomInDescription: return " 확대";
                case XtraRichEditStringId.MenuCmd_ZoomOut: return " 축소";
                case XtraRichEditStringId.MenuCmd_ZoomOutDescription: return " 축소";
                case XtraRichEditStringId.Msg_BookmarkCreationFailing: return " 책갈피와 같은 이름이 이미 존재합니다. 대체?";
                case XtraRichEditStringId.Msg_DocumentProtectionInvalidPassword: return " 암호 올바르지 않습니다!";
                case XtraRichEditStringId.Msg_DocumentProtectionInvalidPasswordConfirmation: return " 암호 확인이 일치 하지 않습니다.";
                case XtraRichEditStringId.Msg_DuplicateBookmark: return " 이미 해당 이름의 책갈피는 문서에 존재";
                case XtraRichEditStringId.Msg_IncorrectBookmarkName: return " 책갈피 이름을 문자로 시작 해야 하며 영숫자 문자와 밑줄.";
                case XtraRichEditStringId.Msg_InternalError: return " 내부 오류가 발생 했습니다";
                case XtraRichEditStringId.Msg_InvalidNumber: return " 이 숫자는 올바르지 않습니다.";
                case XtraRichEditStringId.Msg_InvalidStyleName: return " 잘못된 스타일 이름";
                case XtraRichEditStringId.Msg_InvalidTabStop: return " 이 탭은 올바르지 않습니다.";
                case XtraRichEditStringId.Msg_Loading: return " 로드 중...";
                case XtraRichEditStringId.Msg_NoTocEntriesFound: return " 목차 항목을 찾을 수 없습니다.";
                case XtraRichEditStringId.Msg_Saving: return " 저장...";
                case XtraRichEditStringId.Msg_SearchComplete: return " 검색이 완료되었습니다.";
                case XtraRichEditStringId.Msg_SearchInBackwardDirectionComplete: return " 는 문서의 시작 부분에 도달 했습니다.";
                case XtraRichEditStringId.Msg_SearchInForwardDirectionComplete: return " 문서의 끝 부분입니다.";
                case XtraRichEditStringId.Msg_SearchInSelectionComplete: return " 선택 검색이 완료되었습니다.";
                case XtraRichEditStringId.Msg_SearchItemNotFound: return " 검색 한 항목이 발견되지 않았습니다.";
                case XtraRichEditStringId.Msg_SelectBookmarkError: return " 비활성 하위 책갈피를 선택할 수 없습니다.";
                case XtraRichEditStringId.Msg_SyntaxErrorInFieldPattern: return " 구문 오류 {0}.";
                case XtraRichEditStringId.Msg_UnknownSwitchArgument: return " 오류! 알 수없는 스위치 인수";
                case XtraRichEditStringId.Msg_UnsupportedFormatException: return " 이 파일 형식을 지원하지 않습니다.";
                case XtraRichEditStringId.Msg_UseDeletedBookmarkError: return " 오류: 책갈피 삭제를 사용 하 여";
                case XtraRichEditStringId.Msg_UsedWrongUnit: return " 측정 단위가 올바르게 지정되지 않습니다.";
                case XtraRichEditStringId.Msg_ZeroDivide: return " !0 나누기.";
                case XtraRichEditStringId.TabForm_All: return " 모든";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionAlignmentCenter: return " 가운데";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionAlignmentInside: return " 내부";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionAlignmentLeft: return " 왼쪽";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionAlignmentOutside: return " 외부";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionAlignmentRight: return " 오른쪽";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionTypeColumn: return " 열";
                case XtraRichEditStringId.TablePositioningForm_HorizontalPositionTypePage: return " 페이지";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionAlignmentBottom: return " 하단";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionAlignmentCenter: return " 가운데";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionAlignmentInside: return " 내부";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionAlignmentOutside: return " 외부";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionAlignmentTop: return " 상단";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionTypePage: return " 페이지";
                case XtraRichEditStringId.TablePositioningForm_VerticalPositionTypeParagraph: return " 단락";
                case XtraRichEditStringId.TargetFrameDescription_Blank: return " 새 창";
                case XtraRichEditStringId.TargetFrameDescription_Parent: return " 상위 프레임";
                case XtraRichEditStringId.TargetFrameDescription_Self: return " 같은 프레임";
                case XtraRichEditStringId.TargetFrameDescription_Top: return " 전체 페이지";
                case XtraRichEditStringId.UnderlineNone: return " (없음)";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopLeftAlignment: return " 위쪽 / 왼쪽 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopCenterAlignment: return " 위쪽 / 가운데 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopRightAlignment: return " 위쪽 / 오른쪽 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleLeftAlignment: return " 중간 / 왼쪽 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleCenterAlignment: return " 중간 / 가운데 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleRightAlignment: return " 중간 / 오른쪽 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomLeftAlignment: return " 아래쪽 / 왼쪽 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomCenterAlignment: return " 아래쪽 / 가운데 맞춤";
                case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomRightAlignment: return " 아래쪽 / 오른쪽 맞춤";
            }
            return base.GetLocalizedString(id);
        }

        ///// <summary>
        ///// Editor Control에서 보여지는 Text를 설정합니다.
        ///// </summary>
        ///// <param name="id"></param>
        ///// <returns></returns>
        //public override string GetLocalizedString(XtraRichEditStringId id)
        //{
        //    switch (id)
        //    {
        //        case XtraRichEditStringId.MenuCmd_CutSelection:
        //            return "잘라내기";
        //        case XtraRichEditStringId.MenuCmd_CopySelection:
        //            return "복사";
        //        case XtraRichEditStringId.MenuCmd_Paste:
        //            return "붙여넣기";
        //        case XtraRichEditStringId.MenuCmd_InsertTablesCaption:
        //            return "삽입";
        //        case XtraRichEditStringId.MenuCmd_InsertTableColumnToTheLeft:
        //            return "왼쪽에 열 삽입";
        //        case XtraRichEditStringId.MenuCmd_InsertTableColumnToTheRight:
        //            return "오른쪽에 열 삽입";
        //        case XtraRichEditStringId.MenuCmd_InsertTableRowAbove:
        //            return "위에 행 삽입";
        //        case XtraRichEditStringId.MenuCmd_InsertTableRowBelow:
        //            return "아래에 행 삽입";
        //        case XtraRichEditStringId.MenuCmd_InsertTableCells:
        //            return "셀 삽입";
        //        case XtraRichEditStringId.MenuCmd_DeleteBack:
        //            return "셀 삭제";
        //        case XtraRichEditStringId.MenuCmd_SplitTableCellsMenuItem:
        //            return "셀 분할";
        //        case XtraRichEditStringId.MenuCmd_ChangeTableCellsContentAlignment:
        //            return "맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopLeftAlignment:
        //            return "위쪽 / 왼쪽 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopCenterAlignment:
        //            return "위쪽 / 가운데 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsTopRightAlignment:
        //            return "위쪽 / 오른쪽 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleLeftAlignment:
        //            return "중간 / 왼쪽 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleCenterAlignment:
        //            return "중간 / 가운데 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsMiddleRightAlignment:
        //            return "중간 / 오른쪽 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomLeftAlignment:
        //            return "아래쪽 / 왼쪽 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomCenterAlignment:
        //            return "아래쪽 / 가운데 맞춤";
        //        case XtraRichEditStringId.MenuCmd_ToggleTableCellsBottomRightAlignment:
        //            return "아래쪽 / 오른쪽 맞춤";
        //        case XtraRichEditStringId.MenuCmd_DeleteTable:
        //            return "표 지우기";
        //        case XtraRichEditStringId.MenuCmd_Delete:
        //            return "삭제";
        //        case XtraRichEditStringId.MenuCmd_DecrementIndent:
        //            return "내어쓰기";
        //        case XtraRichEditStringId.MenuCmd_IncrementIndent:
        //            return "들여쓰기";
        //    }
        //    return base.GetLocalizedString(id);
        //}
    }
}
